import java.sql.Connection;
import java.sql.*;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author TesseracT
 */
public class AddBalance extends javax.swing.JFrame {
 String Username1;
 Connection conn=null;
ResultSet rs=null;
PreparedStatement pst=null;

    /**
     * Creates new form AddBalance
     */
    public AddBalance() {
       
        initComponents();
         this.setLocationRelativeTo(null);
    }

    AddBalance(String Username) {
        Username1=Username;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        SP = new javax.swing.JPanel();
        bal = new javax.swing.JLabel();
        add = new javax.swing.JLabel();
        back = new javax.swing.JLabel();
        wallet = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        cc = new javax.swing.JRadioButton();
        ccm = new javax.swing.JPanel();
        custname = new javax.swing.JTextField();
        cno = new javax.swing.JTextField();
        mm = new javax.swing.JComboBox();
        yy = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cvvv = new javax.swing.JLabel();
        CV = new javax.swing.JTextField();
        dc = new javax.swing.JRadioButton();
        dcm = new javax.swing.JPanel();
        custname1 = new javax.swing.JTextField();
        cno1 = new javax.swing.JTextField();
        mm1 = new javax.swing.JComboBox();
        yy1 = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        CV1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        amt = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        SP.setBackground(new java.awt.Color(54, 33, 89));
        SP.setForeground(new java.awt.Color(255, 255, 255));

        bal.setForeground(new java.awt.Color(255, 255, 255));

        back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/icons8_Go_Back_45px.png"))); // NOI18N
        back.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backMouseClicked(evt);
            }
        });

        wallet.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/icons8_wallet_40px.png"))); // NOI18N
        wallet.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        wallet.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                walletMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                walletMouseExited(evt);
            }
        });

        javax.swing.GroupLayout SPLayout = new javax.swing.GroupLayout(SP);
        SP.setLayout(SPLayout);
        SPLayout.setHorizontalGroup(
            SPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SPLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(back)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(wallet)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(SPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bal, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(add, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19))
        );
        SPLayout.setVerticalGroup(
            SPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SPLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(add, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bal, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
            .addGroup(SPLayout.createSequentialGroup()
                .addComponent(back, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(wallet, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        cc.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(cc);
        cc.setText("Credit Card");
        cc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ccMouseClicked(evt);
            }
        });

        ccm.setBackground(new java.awt.Color(255, 255, 255));

        mm.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Expiry MM", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12" }));

        yy.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Expiry YYYY", "2019", "2020", "2021", "2022", "2023", "2024", "2025", "2026", "2027", "2028", "2029", "2030", "2031", "2032" }));

        jLabel3.setText("Name");

        jLabel4.setText("Card Number");

        cvvv.setText("CVV");

        javax.swing.GroupLayout ccmLayout = new javax.swing.GroupLayout(ccm);
        ccm.setLayout(ccmLayout);
        ccmLayout.setHorizontalGroup(
            ccmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ccmLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ccmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ccmLayout.createSequentialGroup()
                        .addGroup(ccmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(ccmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cno, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(custname, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(ccmLayout.createSequentialGroup()
                        .addGroup(ccmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(mm, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cvvv))
                        .addGroup(ccmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(ccmLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(yy, 0, 110, Short.MAX_VALUE))
                            .addGroup(ccmLayout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(CV)))))
                .addContainerGap())
        );
        ccmLayout.setVerticalGroup(
            ccmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ccmLayout.createSequentialGroup()
                .addGroup(ccmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(custname, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(ccmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ccmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(yy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addGroup(ccmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cvvv)
                    .addComponent(CV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        dc.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(dc);
        dc.setText("Debit Card");
        dc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dcMouseClicked(evt);
            }
        });

        dcm.setBackground(new java.awt.Color(255, 255, 255));

        mm1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Expiry MM", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12" }));

        yy1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Expiry YYYY", "2019", "2020", "2021", "2022", "2023", "2024", "2025", "2026", "2027", "2028", "2029", "2030", "2031", "2032" }));

        jLabel7.setText("Name");

        jLabel8.setText("Card Number");

        jLabel9.setText("CVV");

        javax.swing.GroupLayout dcmLayout = new javax.swing.GroupLayout(dcm);
        dcm.setLayout(dcmLayout);
        dcmLayout.setHorizontalGroup(
            dcmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dcmLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dcmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dcmLayout.createSequentialGroup()
                        .addComponent(mm1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(yy1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(dcmLayout.createSequentialGroup()
                        .addGroup(dcmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(dcmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(custname1, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE)
                            .addComponent(cno1)))
                    .addGroup(dcmLayout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(CV1, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        dcmLayout.setVerticalGroup(
            dcmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dcmLayout.createSequentialGroup()
                .addGroup(dcmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(custname1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(8, 8, 8)
                .addGroup(dcmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cno1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dcmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mm1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(yy1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(dcmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(CV1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ccm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(dc)
                    .addComponent(dcm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cc))
                .addGap(23, 23, 23))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cc, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ccm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dc, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dcm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 110, -1, -1));

        jLabel1.setFont(new java.awt.Font("Serif", 1, 24)); // NOI18N
        jLabel1.setText("Select a payment method");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 70, -1, -1));

        jLabel5.setFont(new java.awt.Font("Serif", 1, 21)); // NOI18N
        jLabel5.setText("Amount :");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 30, -1, -1));

        amt.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        jPanel1.add(amt, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 30, 319, 32));

        jLabel6.setFont(new java.awt.Font("Serif", 0, 21)); // NOI18N
        jLabel6.setText("Rs.");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 30, -1, -1));

        jButton1.setBackground(new java.awt.Color(255, 153, 51));
        jButton1.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        jButton1.setText("Pay Now");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 460, -1, 50));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/background.jpg"))); // NOI18N
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 970, 560));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(SP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(SP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dcMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dcMouseClicked
   if (dc.isSelected())
   {dcm.setVisible(true);
   ccm.setVisible(false);}
        else 
dcm.setVisible(false);
     // TODO add your handling code here:
    }//GEN-LAST:event_dcMouseClicked

    private void ccMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ccMouseClicked
  if (cc.isSelected())
  {ccm.setVisible(true);
  dcm.setVisible(false);}
   else 
ccm.setVisible(false);

      // TODO add your handling code here:
    }//GEN-LAST:event_ccMouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
   ccm.setVisible(false); 
     dcm.setVisible(false);
     String sql = "select Balance from user_details where User_name=('"+ Username1 +"')"; 
       try{ Class.forName("com.mysql.jdbc.Driver");
         Connection con =DriverManager.getConnection("jdbc:mysql://localhost/project2019","root","0000");
        
       pst=con.prepareStatement(sql);
       rs=pst.executeQuery();                    
                          
     
       while (rs.next()){ 
        bal.setText(rs.getString("Balance"));}
              }
   catch(Exception e){       
       System.out.println("Something went wrong !! Please try again");} // TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
int amount=Integer.parseInt(amt.getText());
int bln=Integer.parseInt(bal.getText());
int tamt=amount+bln;
String cname=custname.getText();
String cname1=custname1.getText();
String card=cno.getText();
String card1=cno1.getText();
String mo=(String) mm.getSelectedItem();
String ye=(String) yy.getSelectedItem();
String mo1=(String)mm1.getSelectedItem();
String ye1=(String) yy1.getSelectedItem();
String cv=CV.getText();
String cv1=CV1.getText();
String ctype = null,cn = null,cardno = null,cvv = null;
String mon = null,yr = null;

if (dc.isSelected())
{cn =cname1;
        cardno =card1; 
        mon=mo1;
        yr=ye1;
        ctype="Debit";
        cvv=cv;
}
else if (cc.isSelected()){
cn =cname;
        cardno =card; 
        mon=mo;
        yr=ye;
          ctype="Credit";
          cvv=cv1;
}
   try
     {
         Class.forName("com.mysql.jdbc.Driver");
         Connection con =DriverManager.getConnection("jdbc:mysql://localhost/project2019","root","0000");
         Statement stmt=con.createStatement();

         

       String insert="INSERT INTO appaccountdetails VALUES('"+ cn +"','"+ cardno +"','"+ cvv +"','"+ amount +"','"+Username1+"','"+ctype +"','"+mon+"','"+yr +"');";
        String update="UPDATE user_details SET Balance="+ tamt +" WHERE User_Name = '"+ Username1 +"';";
       stmt.executeUpdate(insert);
        stmt.executeUpdate(update);

       JOptionPane.showMessageDialog(null,"Balance Added Successfully");
       this.dispose();
     }
     catch(Exception e)
     {
         JOptionPane.showMessageDialog(null, e.getMessage() ,"Error", 1);

     }
           
// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void backMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseClicked
        this.dispose();       // TODO add your handling code here:
    }//GEN-LAST:event_backMouseClicked

    private void walletMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_walletMouseEntered
        wallet.setToolTipText("Add Balance") ;
        wallet.setIcon(new ImageIcon(getClass().getResource("/Resources/icons8_wallet_32px.png")));
        add.setIcon(new ImageIcon(getClass().getResource("/Resources/icons8_add_16px_1.png")));

        String sql = "select Balance from user_details where User_name=('"+ Username1 +"')";
        try{ Class.forName("com.mysql.jdbc.Driver");
            Connection con =DriverManager.getConnection("jdbc:mysql://localhost/project2019","root","0000");

            pst=con.prepareStatement(sql);
            rs=pst.executeQuery();

            while (rs.next()){
                bal.setText(rs.getString("Balance"));}
        }
        catch(Exception e){
            System.out.println("Something went wrong !! Please try again");}// TODO add your handling code here:
    }//GEN-LAST:event_walletMouseEntered

    private void walletMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_walletMouseExited
        wallet.setIcon(new ImageIcon(getClass().getResource("/Resources/icons8_wallet_40px.png")));
        add.setIcon(null);
        // TODO add your handling code here:
    }//GEN-LAST:event_walletMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddBalance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddBalance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddBalance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddBalance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddBalance().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CV;
    private javax.swing.JTextField CV1;
    private javax.swing.JPanel SP;
    private javax.swing.JLabel add;
    private javax.swing.JTextField amt;
    private javax.swing.JLabel back;
    private javax.swing.JLabel bal;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton cc;
    private javax.swing.JPanel ccm;
    private javax.swing.JTextField cno;
    private javax.swing.JTextField cno1;
    private javax.swing.JTextField custname;
    private javax.swing.JTextField custname1;
    private javax.swing.JLabel cvvv;
    private javax.swing.JRadioButton dc;
    private javax.swing.JPanel dcm;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JComboBox mm;
    private javax.swing.JComboBox mm1;
    private javax.swing.JLabel wallet;
    private javax.swing.JComboBox yy;
    private javax.swing.JComboBox yy1;
    // End of variables declaration//GEN-END:variables
}
