
import java.awt.Color;
import java.sql.*;
import javax.swing.ImageIcon;





/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author TesseracT
 */
public class Books extends javax.swing.JFrame {
String Username1;
Connection conn=null;
ResultSet rs=null;
int curRow=0;
    /**
     * Creates new form Books
     */
    public Books() {
        initComponents();
        
    }

    Books(String Username) {
       Username1=Username;
        initComponents();//To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MP = new javax.swing.JPanel();
        BooksSp = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        BooksSym = new javax.swing.JLabel();
        Books = new javax.swing.JLabel();
        HomeSp = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        HomeSym = new javax.swing.JLabel();
        Home = new javax.swing.JLabel();
        ElectronicsSp = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        ElectronicsSym = new javax.swing.JLabel();
        Electronics = new javax.swing.JLabel();
        GrocerySp = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        GrocerySym = new javax.swing.JLabel();
        Grocery = new javax.swing.JLabel();
        SportsSp = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        SportsSym = new javax.swing.JLabel();
        Sports = new javax.swing.JLabel();
        MyOSp = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        MyOSym = new javax.swing.JLabel();
        MyO = new javax.swing.JLabel();
        MyCSp = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        MyCSym = new javax.swing.JLabel();
        MyC = new javax.swing.JLabel();
        MyASp = new javax.swing.JPanel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        MyASym = new javax.swing.JLabel();
        MyA = new javax.swing.JLabel();
        RPOP = new javax.swing.JPanel();
        RPOI = new javax.swing.JLabel();
        RPOC = new javax.swing.JLabel();
        LMPP = new javax.swing.JPanel();
        LMPC = new javax.swing.JLabel();
        LMPI = new javax.swing.JLabel();
        TPOFSMP = new javax.swing.JPanel();
        TPOFSMC = new javax.swing.JLabel();
        TPOYSMI = new javax.swing.JLabel();
        TCNOSHP = new javax.swing.JPanel();
        TCNOSHI = new javax.swing.JLabel();
        TCNOSHC = new javax.swing.JLabel();
        PNIDEP = new javax.swing.JPanel();
        PNIDEI = new javax.swing.JLabel();
        PNIDEC = new javax.swing.JLabel();
        SASP = new javax.swing.JPanel();
        SASI = new javax.swing.JLabel();
        SASC = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        bal = new javax.swing.JLabel();
        wallet = new javax.swing.JLabel();
        add = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        MP.setBackground(new java.awt.Color(54, 33, 89));

        BooksSp.setBackground(new java.awt.Color(255, 255, 255));
        BooksSp.setForeground(new java.awt.Color(255, 255, 255));
        BooksSp.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        BooksSp.setLayout(new javax.swing.BoxLayout(BooksSp, javax.swing.BoxLayout.LINE_AXIS));
        BooksSp.add(jLabel1);

        jLabel4.setText("      ");
        BooksSp.add(jLabel4);

        BooksSym.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/icons8_book_shelf_30px_1.png"))); // NOI18N
        BooksSym.setText("    ");
        BooksSp.add(BooksSym);

        Books.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Books.setForeground(new java.awt.Color(85, 65, 118));
        Books.setText("    Books");
        Books.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        BooksSp.add(Books);

        HomeSp.setBackground(new java.awt.Color(85, 65, 118));
        HomeSp.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        HomeSp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HomeSpMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                HomeSpMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                HomeSpMouseExited(evt);
            }
        });
        HomeSp.setLayout(new javax.swing.BoxLayout(HomeSp, javax.swing.BoxLayout.LINE_AXIS));
        HomeSp.add(jLabel5);

        jLabel6.setText("      ");
        HomeSp.add(jLabel6);

        HomeSym.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/icons8_home_30px_1.png"))); // NOI18N
        HomeSym.setText("    ");
        HomeSym.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HomeSymMouseClicked(evt);
            }
        });
        HomeSp.add(HomeSym);

        Home.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Home.setForeground(new java.awt.Color(204, 204, 204));
        Home.setText("    Home");
        Home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HomeMouseClicked(evt);
            }
        });
        HomeSp.add(Home);

        ElectronicsSp.setBackground(new java.awt.Color(85, 65, 118));
        ElectronicsSp.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ElectronicsSp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ElectronicsSpMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ElectronicsSpMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ElectronicsSpMouseExited(evt);
            }
        });
        ElectronicsSp.setLayout(new javax.swing.BoxLayout(ElectronicsSp, javax.swing.BoxLayout.LINE_AXIS));
        ElectronicsSp.add(jLabel9);

        jLabel10.setText("      ");
        ElectronicsSp.add(jLabel10);

        ElectronicsSym.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/icons8_electronics_30px_1.png"))); // NOI18N
        ElectronicsSym.setText("    ");
        ElectronicsSym.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ElectronicsSymMouseClicked(evt);
            }
        });
        ElectronicsSp.add(ElectronicsSym);

        Electronics.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Electronics.setForeground(new java.awt.Color(204, 204, 204));
        Electronics.setText("    Electronics");
        Electronics.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ElectronicsMouseClicked(evt);
            }
        });
        ElectronicsSp.add(Electronics);

        GrocerySp.setBackground(new java.awt.Color(85, 65, 118));
        GrocerySp.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        GrocerySp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                GrocerySpMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                GrocerySpMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                GrocerySpMouseExited(evt);
            }
        });
        GrocerySp.setLayout(new javax.swing.BoxLayout(GrocerySp, javax.swing.BoxLayout.LINE_AXIS));
        GrocerySp.add(jLabel13);

        jLabel14.setText("      ");
        GrocerySp.add(jLabel14);

        GrocerySym.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/icons8_grocery_bag_30px.png"))); // NOI18N
        GrocerySym.setText("    ");
        GrocerySym.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                GrocerySymMouseClicked(evt);
            }
        });
        GrocerySp.add(GrocerySym);

        Grocery.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Grocery.setForeground(new java.awt.Color(204, 204, 204));
        Grocery.setText("    Grocery");
        Grocery.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                GroceryMouseClicked(evt);
            }
        });
        GrocerySp.add(Grocery);

        SportsSp.setBackground(new java.awt.Color(85, 65, 118));
        SportsSp.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        SportsSp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SportsSpMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                SportsSpMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                SportsSpMouseExited(evt);
            }
        });
        SportsSp.setLayout(new javax.swing.BoxLayout(SportsSp, javax.swing.BoxLayout.LINE_AXIS));
        SportsSp.add(jLabel17);

        jLabel18.setText("      ");
        SportsSp.add(jLabel18);

        SportsSym.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/icons8_volleyball_2_30px_1.png"))); // NOI18N
        SportsSym.setText("    ");
        SportsSym.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SportsSymMouseClicked(evt);
            }
        });
        SportsSp.add(SportsSym);

        Sports.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Sports.setForeground(new java.awt.Color(204, 204, 204));
        Sports.setText("    Sports,Fitness & Bags ");
        Sports.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SportsMouseClicked(evt);
            }
        });
        SportsSp.add(Sports);

        MyOSp.setBackground(new java.awt.Color(85, 65, 118));
        MyOSp.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        MyOSp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MyOSpMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                MyOSpMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                MyOSpMouseExited(evt);
            }
        });
        MyOSp.setLayout(new javax.swing.BoxLayout(MyOSp, javax.swing.BoxLayout.LINE_AXIS));
        MyOSp.add(jLabel21);

        jLabel23.setText("     ");
        MyOSp.add(jLabel23);

        MyOSym.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/icons8_purchase_order_32px.png"))); // NOI18N
        MyOSym.setText("      ");
        MyOSym.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MyOSymMouseClicked(evt);
            }
        });
        MyOSp.add(MyOSym);

        MyO.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        MyO.setForeground(new java.awt.Color(204, 204, 204));
        MyO.setText("     My Orders");
        MyO.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MyOMouseClicked(evt);
            }
        });
        MyOSp.add(MyO);

        MyCSp.setBackground(new java.awt.Color(85, 65, 118));
        MyCSp.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        MyCSp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MyCSpMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                MyCSpMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                MyCSpMouseExited(evt);
            }
        });
        MyCSp.setLayout(new javax.swing.BoxLayout(MyCSp, javax.swing.BoxLayout.LINE_AXIS));
        MyCSp.add(jLabel25);

        jLabel26.setText("      ");
        MyCSp.add(jLabel26);

        MyCSym.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/icons8_shopping_cart_30px.png"))); // NOI18N
        MyCSym.setText("    ");
        MyCSym.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MyCSymMouseClicked(evt);
            }
        });
        MyCSp.add(MyCSym);

        MyC.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        MyC.setForeground(new java.awt.Color(204, 204, 204));
        MyC.setText("      My Cart");
        MyC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MyCMouseClicked(evt);
            }
        });
        MyCSp.add(MyC);

        MyASp.setBackground(new java.awt.Color(85, 65, 118));
        MyASp.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        MyASp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MyASpMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                MyASpMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                MyASpMouseExited(evt);
            }
        });
        MyASp.setLayout(new javax.swing.BoxLayout(MyASp, javax.swing.BoxLayout.LINE_AXIS));
        MyASp.add(jLabel29);

        jLabel30.setText("      ");
        MyASp.add(jLabel30);

        MyASym.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/icons8_user_male_circle_30px.png"))); // NOI18N
        MyASym.setText("    ");
        MyASym.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MyASymMouseClicked(evt);
            }
        });
        MyASp.add(MyASym);

        MyA.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        MyA.setForeground(new java.awt.Color(204, 204, 204));
        MyA.setText("      My Account ");
        MyA.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MyAMouseClicked(evt);
            }
        });
        MyASp.add(MyA);

        javax.swing.GroupLayout MPLayout = new javax.swing.GroupLayout(MP);
        MP.setLayout(MPLayout);
        MPLayout.setHorizontalGroup(
            MPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MPLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(MPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MPLayout.createSequentialGroup()
                        .addGroup(MPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ElectronicsSp, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(GrocerySp, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BooksSp, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SportsSp, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(MyOSp, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(MyASp, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MPLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(MPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(MyCSp, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(HomeSp, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        MPLayout.setVerticalGroup(
            MPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MPLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(HomeSp, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(108, 108, 108)
                .addComponent(BooksSp, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ElectronicsSp, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(GrocerySp, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SportsSp, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(89, 89, 89)
                .addComponent(MyOSp, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(MyCSp, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(MyASp, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        RPOP.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        RPOP.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        RPOP.setPreferredSize(new java.awt.Dimension(325, 323));

        RPOI.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/ReadyPlayerOne.jpeg"))); // NOI18N
        RPOI.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        RPOI.setMaximumSize(new java.awt.Dimension(337, 323));
        RPOI.setMinimumSize(new java.awt.Dimension(325, 330));
        RPOI.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RPOIMouseClicked(evt);
            }
        });

        RPOC.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        RPOC.setText("Ready Player One");

        javax.swing.GroupLayout RPOPLayout = new javax.swing.GroupLayout(RPOP);
        RPOP.setLayout(RPOPLayout);
        RPOPLayout.setHorizontalGroup(
            RPOPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(RPOI, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RPOPLayout.createSequentialGroup()
                .addContainerGap(107, Short.MAX_VALUE)
                .addComponent(RPOC)
                .addGap(105, 105, 105))
        );
        RPOPLayout.setVerticalGroup(
            RPOPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RPOPLayout.createSequentialGroup()
                .addComponent(RPOI, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(RPOC, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        LMPP.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        LMPP.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        LMPC.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        LMPC.setText("Learning More Python 3 the Hard Way");
        LMPC.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        LMPI.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/WhatsApp Image 2019-05-17 at 10.05.54 PM.jpeg"))); // NOI18N
        LMPI.setText(" ");
        LMPI.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        javax.swing.GroupLayout LMPPLayout = new javax.swing.GroupLayout(LMPP);
        LMPP.setLayout(LMPPLayout);
        LMPPLayout.setHorizontalGroup(
            LMPPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LMPPLayout.createSequentialGroup()
                .addComponent(LMPI, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(LMPPLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(LMPC)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        LMPPLayout.setVerticalGroup(
            LMPPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LMPPLayout.createSequentialGroup()
                .addComponent(LMPI, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(LMPC)
                .addContainerGap())
        );

        TPOFSMP.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        TPOFSMP.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        TPOFSMC.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        TPOFSMC.setText("The Power Of Your Subconscious Mind");
        TPOFSMC.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        TPOYSMI.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/ThePowerOfyourSubconciousMind.jpeg"))); // NOI18N
        TPOYSMI.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        javax.swing.GroupLayout TPOFSMPLayout = new javax.swing.GroupLayout(TPOFSMP);
        TPOFSMP.setLayout(TPOFSMPLayout);
        TPOFSMPLayout.setHorizontalGroup(
            TPOFSMPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TPOFSMPLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(TPOFSMPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(TPOFSMPLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(TPOFSMC))
                    .addComponent(TPOYSMI, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        TPOFSMPLayout.setVerticalGroup(
            TPOFSMPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TPOFSMPLayout.createSequentialGroup()
                .addComponent(TPOYSMI)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(TPOFSMC)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        TCNOSHP.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        TCNOSHP.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        TCNOSHP.setPreferredSize(new java.awt.Dimension(325, 323));

        TCNOSHI.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/SherlockHolmes.jpeg"))); // NOI18N
        TCNOSHI.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        TCNOSHC.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        TCNOSHC.setText("The Complete Novels of Sherlock Holmes");
        TCNOSHC.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        javax.swing.GroupLayout TCNOSHPLayout = new javax.swing.GroupLayout(TCNOSHP);
        TCNOSHP.setLayout(TCNOSHPLayout);
        TCNOSHPLayout.setHorizontalGroup(
            TCNOSHPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TCNOSHPLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TCNOSHI, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TCNOSHPLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(TCNOSHC)
                .addGap(21, 21, 21))
        );
        TCNOSHPLayout.setVerticalGroup(
            TCNOSHPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TCNOSHPLayout.createSequentialGroup()
                .addComponent(TCNOSHI)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TCNOSHC)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        PNIDEP.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        PNIDEP.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        PNIDEP.setPreferredSize(new java.awt.Dimension(340, 495));

        PNIDEI.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/NetBeans.jpeg"))); // NOI18N
        PNIDEI.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        PNIDEC.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        PNIDEC.setText("Pro Netbeans IDE 6 Rich Client Platform Edition");
        PNIDEC.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        javax.swing.GroupLayout PNIDEPLayout = new javax.swing.GroupLayout(PNIDEP);
        PNIDEP.setLayout(PNIDEPLayout);
        PNIDEPLayout.setHorizontalGroup(
            PNIDEPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PNIDEPLayout.createSequentialGroup()
                .addComponent(PNIDEC)
                .addGap(0, 6, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PNIDEPLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(PNIDEI, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38))
        );
        PNIDEPLayout.setVerticalGroup(
            PNIDEPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PNIDEPLayout.createSequentialGroup()
                .addComponent(PNIDEI)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(PNIDEC)
                .addContainerGap())
        );

        SASP.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        SASP.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        SASP.setPreferredSize(new java.awt.Dimension(340, 495));

        SASI.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Simulation.jpeg"))); // NOI18N
        SASI.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        SASC.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        SASC.setText("Simulacra and Simulation");
        SASC.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        javax.swing.GroupLayout SASPLayout = new javax.swing.GroupLayout(SASP);
        SASP.setLayout(SASPLayout);
        SASPLayout.setHorizontalGroup(
            SASPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SASPLayout.createSequentialGroup()
                .addGroup(SASPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(SASPLayout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(SASC))
                    .addGroup(SASPLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(SASI, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        SASPLayout.setVerticalGroup(
            SASPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SASPLayout.createSequentialGroup()
                .addComponent(SASI)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SASC)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(54, 33, 89));

        bal.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        bal.setForeground(new java.awt.Color(255, 255, 255));

        wallet.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/icons8_wallet_40px.png"))); // NOI18N
        wallet.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        wallet.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                walletMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                walletMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                walletMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(wallet)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(add, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bal, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(wallet, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(add, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bal, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 15, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(MP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TCNOSHP, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(RPOP, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(PNIDEP, javax.swing.GroupLayout.DEFAULT_SIZE, 339, Short.MAX_VALUE)
                            .addComponent(LMPP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(TPOFSMP, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SASP, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(TPOFSMP, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(LMPP, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(RPOP, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(TCNOSHP, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE)
                    .addComponent(PNIDEP, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE)
                    .addComponent(SASP, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MyOMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MyOMouseClicked
MyOrders mo= new MyOrders(Username1);
        mo.setVisible(true);
        this.dispose();   //Connecting it with MyOrders Frame    
    }//GEN-LAST:event_MyOMouseClicked

    private void RPOIMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RPOIMouseClicked
  ReadyPlayerOneBook rp= new ReadyPlayerOneBook(Username1);
        rp.setVisible(true);
        this.dispose();  //Connecting Book with its Frame              
    }//GEN-LAST:event_RPOIMouseClicked

    private void ElectronicsSymMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ElectronicsSymMouseClicked
 Electronics er= new Electronics(Username1);
        er.setVisible(true);
        this.dispose();        //Connecting it with Electronics Frame   
    }//GEN-LAST:event_ElectronicsSymMouseClicked

    private void ElectronicsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ElectronicsMouseClicked
Electronics er= new Electronics(Username1);
        er.setVisible(true);
        this.dispose();        //Connecting it with Electronics Frame     
    }//GEN-LAST:event_ElectronicsMouseClicked

    private void GrocerySymMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GrocerySymMouseClicked
Grocery gr= new Grocery(Username1);
        gr.setVisible(true);
        this.dispose();         //Connecting it with Grocery Frame   
    }//GEN-LAST:event_GrocerySymMouseClicked

    private void GroceryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GroceryMouseClicked
Grocery gr= new Grocery(Username1);
        gr.setVisible(true);
        this.dispose();           //Connecting it with Grocery Frame  
    }//GEN-LAST:event_GroceryMouseClicked

    private void SportsSymMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SportsSymMouseClicked
SportsFitnessBags sfb= new SportsFitnessBags(Username1);
        sfb.setVisible(true);
        this.dispose();      //Connecting it with Sports,Fitness&Bags Frame      
    }//GEN-LAST:event_SportsSymMouseClicked

    private void SportsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SportsMouseClicked
SportsFitnessBags sfb= new SportsFitnessBags(Username1);
        sfb.setVisible(true);
        this.dispose();           //Connecting it with Sports,Fitness&Bags Frame   
    }//GEN-LAST:event_SportsMouseClicked

    private void HomeSymMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HomeSymMouseClicked
MainInterfacee mi= new MainInterfacee(Username1);
        mi.setVisible(true);
        this.dispose();           //Connecting it with Home Frame   
    }//GEN-LAST:event_HomeSymMouseClicked

    private void HomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HomeMouseClicked
MainInterfacee mi= new MainInterfacee(Username1);
        mi.setVisible(true);
        this.dispose();          //Connecting it with Home Frame
    }//GEN-LAST:event_HomeMouseClicked

    private void HomeSpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HomeSpMouseClicked
MainInterfacee mi= new MainInterfacee(Username1);
        mi.setVisible(true);
        this.dispose();        //Connecting it with Home Frame
    }//GEN-LAST:event_HomeSpMouseClicked

    private void ElectronicsSpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ElectronicsSpMouseClicked
 Electronics er= new Electronics(Username1);
        er.setVisible(true);
        this.dispose();       //Connecting it with Electronics Frame
    }//GEN-LAST:event_ElectronicsSpMouseClicked

    private void GrocerySpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GrocerySpMouseClicked
    Grocery gr= new Grocery(Username1);
        gr.setVisible(true);
        this.dispose();        
    }//GEN-LAST:event_GrocerySpMouseClicked

    private void SportsSpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SportsSpMouseClicked
  SportsFitnessBags sfb= new SportsFitnessBags(Username1);
        sfb.setVisible(true);
        this.dispose();       // TODO add your handling code here:
    }//GEN-LAST:event_SportsSpMouseClicked

    private void MyOSpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MyOSpMouseClicked
   MyOrders mo= new MyOrders(Username1);
        mo.setVisible(true);
        this.dispose();         // TODO add your handling code here:
    }//GEN-LAST:event_MyOSpMouseClicked

    private void MyOSymMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MyOSymMouseClicked
MyOrders mo= new MyOrders(Username1);
        mo.setVisible(true);
        this.dispose();          // TODO add your handling code here:
    }//GEN-LAST:event_MyOSymMouseClicked

    private void MyCSymMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MyCSymMouseClicked
MyCart myc= new MyCart(Username1);
        myc.setVisible(true);
        this.dispose();          // TODO add your handling code here:
    }//GEN-LAST:event_MyCSymMouseClicked

    private void MyCMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MyCMouseClicked
MyCart myc= new MyCart(Username1);
        myc.setVisible(true);
        this.dispose();            // TODO add your handling code here:
    }//GEN-LAST:event_MyCMouseClicked

    private void MyCSpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MyCSpMouseClicked
MyCart myc= new MyCart(Username1);
        myc.setVisible(true);
        this.dispose();            // TODO add your handling code here:
    }//GEN-LAST:event_MyCSpMouseClicked

    private void MyASymMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MyASymMouseClicked
MyAccount ma= new MyAccount(Username1);
        ma.setVisible(true);
        this.dispose();          // TODO add your handling code here:
    }//GEN-LAST:event_MyASymMouseClicked

    private void MyAMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MyAMouseClicked
MyAccount ma= new MyAccount(Username1);
        ma.setVisible(true);
        this.dispose();            // TODO add your handling code here:
    }//GEN-LAST:event_MyAMouseClicked

    private void MyASpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MyASpMouseClicked
MyAccount ma= new MyAccount(Username1);
        ma.setVisible(true);
        this.dispose();            // TODO add your handling code here:
    }//GEN-LAST:event_MyASpMouseClicked

    private void HomeSpMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HomeSpMouseEntered

 HomeSym.setIcon(new ImageIcon(getClass().getResource("/Resources/icons8_home_30px.png")));     
   HomeSp.setBackground(Color.WHITE);  
Home.setForeground(new Color(85,65,118));        // TODO add your handling code here:
    }//GEN-LAST:event_HomeSpMouseEntered

    private void HomeSpMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HomeSpMouseExited
  
       HomeSym.setIcon(new ImageIcon(getClass().getResource("/Resources/icons8_home_30px_1.png")));     
        HomeSp.setBackground(new Color(85,65,118));  
Home.setForeground(Color.WHITE);          // TODO add your handling code here:
    }//GEN-LAST:event_HomeSpMouseExited

    private void ElectronicsSpMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ElectronicsSpMouseEntered
ElectronicsSp.setBackground(Color.WHITE);  
Electronics.setForeground(new Color(85,65,118));        // TODO add your handling code here:
    }//GEN-LAST:event_ElectronicsSpMouseEntered

    private void ElectronicsSpMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ElectronicsSpMouseExited
ElectronicsSp.setBackground(new Color(85,65,118));  
Electronics.setForeground(Color.WHITE);        // TODO add your handling code here:
    }//GEN-LAST:event_ElectronicsSpMouseExited

    private void GrocerySpMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GrocerySpMouseEntered
GrocerySp.setBackground(Color.WHITE);  
Grocery.setForeground(new Color(85,65,118));         // TODO add your handling code here:
    }//GEN-LAST:event_GrocerySpMouseEntered

    private void GrocerySpMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GrocerySpMouseExited
 GrocerySp.setBackground(new Color(85,65,118));  
Grocery.setForeground(Color.WHITE);         // TODO add your handling code here:
    }//GEN-LAST:event_GrocerySpMouseExited

    private void SportsSpMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SportsSpMouseEntered
SportsSp.setBackground(Color.WHITE);  
Sports.setForeground(new Color(85,65,118));          // TODO add your handling code here:
    }//GEN-LAST:event_SportsSpMouseEntered

    private void SportsSpMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SportsSpMouseExited
SportsSp.setBackground(new Color(85,65,118));  
Sports.setForeground(Color.WHITE);          // TODO add your handling code here:
    }//GEN-LAST:event_SportsSpMouseExited

    private void MyOSpMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MyOSpMouseEntered
MyOSym.setIcon(new ImageIcon(getClass().getResource("/Resources/icons8_purchase_order_32px_1.png")));  
MyOSp.setBackground(Color.WHITE);  
MyO.setForeground(new Color(85,65,118));       // TODO add your handling code here:
    }//GEN-LAST:event_MyOSpMouseEntered

    private void MyOSpMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MyOSpMouseExited
MyOSym.setIcon(new ImageIcon(getClass().getResource("/Resources/icons8_purchase_order_32px.png")));   
MyOSp.setBackground(new Color(85,65,118));  
MyO.setForeground(Color.WHITE);      // TODO add your handling code here:
    }//GEN-LAST:event_MyOSpMouseExited

    private void MyCSpMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MyCSpMouseEntered
MyCSym.setIcon(new ImageIcon(getClass().getResource("/Resources/icons8_shopping_cart_30px_1.png")));  
        MyCSp.setBackground(Color.WHITE);  
MyC.setForeground(new Color(85,65,118));         // TODO add your handling code here:
    }//GEN-LAST:event_MyCSpMouseEntered

    private void MyCSpMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MyCSpMouseExited
 MyCSym.setIcon(new ImageIcon(getClass().getResource("/Resources/icons8_shopping_cart_30px.png")));  
        MyCSp.setBackground(new Color(85,65,118));  
MyC.setForeground(Color.WHITE);       // TODO add your handling code here:
    }//GEN-LAST:event_MyCSpMouseExited

    private void MyASpMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MyASpMouseEntered
MyASym.setIcon(new ImageIcon(getClass().getResource("/Resources/icons8_user_male_circle_30px_1.png")));  
        MyASp.setBackground(Color.WHITE);  
MyA.setForeground(new Color(85,65,118));        // TODO add your handling code here:
    }//GEN-LAST:event_MyASpMouseEntered

    private void MyASpMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MyASpMouseExited
MyASym.setIcon(new ImageIcon(getClass().getResource("/Resources/icons8_user_male_circle_30px.png")));  
        MyASp.setBackground(new Color(85,65,118));  
MyA.setForeground(Color.WHITE);        // TODO add your handling code here:
    }//GEN-LAST:event_MyASpMouseExited

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
  String sql = "select Balance from user_details where User_name=('"+ Username1 +"')"; 
       try{ Class.forName("com.mysql.jdbc.Driver");
         Connection con =DriverManager.getConnection("jdbc:mysql://localhost/project2019","root","0000");
         Statement stmt=con.createStatement();
      rs= stmt.executeQuery(sql);
                           
       while (rs.next()){ 
       bal.setText(rs.getString("Balance"));}
          stmt.close();
       rs.close();
       con.close();  }
   catch(Exception e){       
       System.out.println("Something went wrong !! Please try again");}      
    this.setLocationRelativeTo(null);  //centre form in the screen

           // TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    private void walletMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_walletMouseClicked
        AddBalance ab= new AddBalance(Username1);
        ab.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_walletMouseClicked

    private void walletMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_walletMouseEntered
        wallet.setToolTipText("Add Balance") ;
        wallet.setIcon(new ImageIcon(getClass().getResource("/Resources/icons8_wallet_32px.png")));
        add.setIcon(new ImageIcon(getClass().getResource("/Resources/icons8_add_16px_1.png")));

        // TODO add your handling code here:
    }//GEN-LAST:event_walletMouseEntered

    private void walletMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_walletMouseExited
        wallet.setIcon(new ImageIcon(getClass().getResource("/Resources/icons8_wallet_40px.png")));
        add.setIcon(null);
        // TODO add your handling code here:
    }//GEN-LAST:event_walletMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Books.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Books.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Books.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Books.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Books().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Books;
    private javax.swing.JPanel BooksSp;
    private javax.swing.JLabel BooksSym;
    private javax.swing.JLabel Electronics;
    private javax.swing.JPanel ElectronicsSp;
    private javax.swing.JLabel ElectronicsSym;
    private javax.swing.JLabel Grocery;
    private javax.swing.JPanel GrocerySp;
    private javax.swing.JLabel GrocerySym;
    private javax.swing.JLabel Home;
    private javax.swing.JPanel HomeSp;
    private javax.swing.JLabel HomeSym;
    private javax.swing.JLabel LMPC;
    private javax.swing.JLabel LMPI;
    private javax.swing.JPanel LMPP;
    private javax.swing.JPanel MP;
    private javax.swing.JLabel MyA;
    private javax.swing.JPanel MyASp;
    private javax.swing.JLabel MyASym;
    private javax.swing.JLabel MyC;
    private javax.swing.JPanel MyCSp;
    private javax.swing.JLabel MyCSym;
    private javax.swing.JLabel MyO;
    private javax.swing.JPanel MyOSp;
    private javax.swing.JLabel MyOSym;
    private javax.swing.JLabel PNIDEC;
    private javax.swing.JLabel PNIDEI;
    private javax.swing.JPanel PNIDEP;
    private javax.swing.JLabel RPOC;
    private javax.swing.JLabel RPOI;
    private javax.swing.JPanel RPOP;
    private javax.swing.JLabel SASC;
    private javax.swing.JLabel SASI;
    private javax.swing.JPanel SASP;
    private javax.swing.JLabel Sports;
    private javax.swing.JPanel SportsSp;
    private javax.swing.JLabel SportsSym;
    private javax.swing.JLabel TCNOSHC;
    private javax.swing.JLabel TCNOSHI;
    private javax.swing.JPanel TCNOSHP;
    private javax.swing.JLabel TPOFSMC;
    private javax.swing.JPanel TPOFSMP;
    private javax.swing.JLabel TPOYSMI;
    private javax.swing.JLabel add;
    private javax.swing.JLabel bal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel wallet;
    // End of variables declaration//GEN-END:variables
}
