
import java.awt.Color;
import java.sql.*;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author TesseracT
 */
public class MyAccount extends javax.swing.JFrame {
String Username1;
Connection conn=null;
ResultSet rs=null;

int curRow=0;
    /**
     * Creates new form MyAccount
     */
    public MyAccount() {
        initComponents();
         
    }

    MyAccount(String Username) {
          Username1=Username;
        initComponents();
    }



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        MP = new javax.swing.JPanel();
        BooksSp = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        BooksSym = new javax.swing.JLabel();
        Books = new javax.swing.JLabel();
        HomeSp = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        HomeSym = new javax.swing.JLabel();
        Home = new javax.swing.JLabel();
        ElectronicsSp = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        ElectronicsSym = new javax.swing.JLabel();
        Electronics = new javax.swing.JLabel();
        GrocerySp = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        GrocerySym = new javax.swing.JLabel();
        Grocery = new javax.swing.JLabel();
        SportsSp = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        SportsSym = new javax.swing.JLabel();
        Sports = new javax.swing.JLabel();
        MyOSp = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        MyOSym = new javax.swing.JLabel();
        MyO = new javax.swing.JLabel();
        MyCSp = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        MyCSym = new javax.swing.JLabel();
        MyC = new javax.swing.JLabel();
        MyASp = new javax.swing.JPanel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        MyASym = new javax.swing.JLabel();
        MyA = new javax.swing.JLabel();
        SP = new javax.swing.JPanel();
        wallet = new javax.swing.JLabel();
        log = new javax.swing.JLabel();
        add = new javax.swing.JLabel();
        bal = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        yn = new javax.swing.JTextField();
        mn = new javax.swing.JTextField();
        eid = new javax.swing.JTextField();
        ci = new javax.swing.JTextField();
        st = new javax.swing.JTextField();
        c = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        ml = new javax.swing.JRadioButton();
        fm = new javax.swing.JRadioButton();
        pre = new javax.swing.JComboBox();
        avatar = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        MP.setBackground(new java.awt.Color(54, 33, 89));

        BooksSp.setBackground(new java.awt.Color(85, 65, 118));
        BooksSp.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BooksSp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BooksSpMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BooksSpMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BooksSpMouseExited(evt);
            }
        });
        BooksSp.setLayout(new javax.swing.BoxLayout(BooksSp, javax.swing.BoxLayout.LINE_AXIS));
        BooksSp.add(jLabel1);

        jLabel4.setText("      ");
        BooksSp.add(jLabel4);

        BooksSym.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/icons8_book_shelf_30px_1.png"))); // NOI18N
        BooksSym.setText("    ");
        BooksSym.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BooksSymMouseClicked(evt);
            }
        });
        BooksSp.add(BooksSym);

        Books.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Books.setForeground(new java.awt.Color(204, 204, 204));
        Books.setText("    Books");
        Books.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Books.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BooksMouseClicked(evt);
            }
        });
        BooksSp.add(Books);

        HomeSp.setBackground(new java.awt.Color(85, 65, 118));
        HomeSp.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        HomeSp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HomeSpMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                HomeSpMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                HomeSpMouseExited(evt);
            }
        });
        HomeSp.setLayout(new javax.swing.BoxLayout(HomeSp, javax.swing.BoxLayout.LINE_AXIS));
        HomeSp.add(jLabel5);

        jLabel6.setText("      ");
        HomeSp.add(jLabel6);

        HomeSym.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/icons8_home_30px_1.png"))); // NOI18N
        HomeSym.setText("    ");
        HomeSym.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HomeSymMouseClicked(evt);
            }
        });
        HomeSp.add(HomeSym);

        Home.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Home.setForeground(new java.awt.Color(204, 204, 204));
        Home.setText("    Home");
        Home.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HomeMouseClicked(evt);
            }
        });
        HomeSp.add(Home);

        ElectronicsSp.setBackground(new java.awt.Color(85, 65, 118));
        ElectronicsSp.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ElectronicsSp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ElectronicsSpMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ElectronicsSpMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ElectronicsSpMouseExited(evt);
            }
        });
        ElectronicsSp.setLayout(new javax.swing.BoxLayout(ElectronicsSp, javax.swing.BoxLayout.LINE_AXIS));
        ElectronicsSp.add(jLabel9);

        jLabel10.setText("      ");
        ElectronicsSp.add(jLabel10);

        ElectronicsSym.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/icons8_electronics_30px_1.png"))); // NOI18N
        ElectronicsSym.setText("    ");
        ElectronicsSym.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ElectronicsSymMouseClicked(evt);
            }
        });
        ElectronicsSp.add(ElectronicsSym);

        Electronics.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Electronics.setForeground(new java.awt.Color(204, 204, 204));
        Electronics.setText("    Electronics");
        Electronics.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ElectronicsMouseClicked(evt);
            }
        });
        ElectronicsSp.add(Electronics);

        GrocerySp.setBackground(new java.awt.Color(85, 65, 118));
        GrocerySp.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        GrocerySp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                GrocerySpMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                GrocerySpMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                GrocerySpMouseExited(evt);
            }
        });
        GrocerySp.setLayout(new javax.swing.BoxLayout(GrocerySp, javax.swing.BoxLayout.LINE_AXIS));
        GrocerySp.add(jLabel13);

        jLabel14.setText("      ");
        GrocerySp.add(jLabel14);

        GrocerySym.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/icons8_grocery_bag_30px.png"))); // NOI18N
        GrocerySym.setText("    ");
        GrocerySym.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                GrocerySymMouseClicked(evt);
            }
        });
        GrocerySp.add(GrocerySym);

        Grocery.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Grocery.setForeground(new java.awt.Color(204, 204, 204));
        Grocery.setText("    Grocery");
        Grocery.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                GroceryMouseClicked(evt);
            }
        });
        GrocerySp.add(Grocery);

        SportsSp.setBackground(new java.awt.Color(85, 65, 118));
        SportsSp.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        SportsSp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SportsSpMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                SportsSpMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                SportsSpMouseExited(evt);
            }
        });
        SportsSp.setLayout(new javax.swing.BoxLayout(SportsSp, javax.swing.BoxLayout.LINE_AXIS));
        SportsSp.add(jLabel17);

        jLabel18.setText("      ");
        SportsSp.add(jLabel18);

        SportsSym.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/icons8_volleyball_2_30px_1.png"))); // NOI18N
        SportsSym.setText("    ");
        SportsSym.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SportsSymMouseClicked(evt);
            }
        });
        SportsSp.add(SportsSym);

        Sports.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Sports.setForeground(new java.awt.Color(204, 204, 204));
        Sports.setText("    Shops,Fitness & Bags ");
        Sports.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SportsMouseClicked(evt);
            }
        });
        SportsSp.add(Sports);

        MyOSp.setBackground(new java.awt.Color(85, 65, 118));
        MyOSp.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        MyOSp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MyOSpMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                MyOSpMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                MyOSpMouseExited(evt);
            }
        });
        MyOSp.setLayout(new javax.swing.BoxLayout(MyOSp, javax.swing.BoxLayout.LINE_AXIS));
        MyOSp.add(jLabel21);

        jLabel23.setText("     ");
        MyOSp.add(jLabel23);

        MyOSym.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/icons8_purchase_order_32px.png"))); // NOI18N
        MyOSym.setText("      ");
        MyOSym.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MyOSymMouseClicked(evt);
            }
        });
        MyOSp.add(MyOSym);

        MyO.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        MyO.setForeground(new java.awt.Color(204, 204, 204));
        MyO.setText("    My Orders");
        MyO.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MyOMouseClicked(evt);
            }
        });
        MyOSp.add(MyO);

        MyCSp.setBackground(new java.awt.Color(85, 65, 118));
        MyCSp.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        MyCSp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MyCSpMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                MyCSpMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                MyCSpMouseExited(evt);
            }
        });
        MyCSp.setLayout(new javax.swing.BoxLayout(MyCSp, javax.swing.BoxLayout.LINE_AXIS));
        MyCSp.add(jLabel25);

        jLabel26.setText("      ");
        MyCSp.add(jLabel26);

        MyCSym.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/icons8_shopping_cart_30px.png"))); // NOI18N
        MyCSym.setText("    ");
        MyCSym.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MyCSymMouseClicked(evt);
            }
        });
        MyCSp.add(MyCSym);

        MyC.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        MyC.setForeground(new java.awt.Color(204, 204, 204));
        MyC.setText("    My Cart");
        MyC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MyCMouseClicked(evt);
            }
        });
        MyCSp.add(MyC);

        MyASp.setBackground(new java.awt.Color(255, 255, 255));
        MyASp.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        MyASp.setLayout(new javax.swing.BoxLayout(MyASp, javax.swing.BoxLayout.LINE_AXIS));
        MyASp.add(jLabel29);

        jLabel30.setText("      ");
        MyASp.add(jLabel30);

        MyASym.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/icons8_user_male_circle_30px_1.png"))); // NOI18N
        MyASym.setText("    ");
        MyASp.add(MyASym);

        MyA.setBackground(new java.awt.Color(255, 255, 255));
        MyA.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        MyA.setForeground(new java.awt.Color(85, 65, 118));
        MyA.setText("    My Account");
        MyASp.add(MyA);

        javax.swing.GroupLayout MPLayout = new javax.swing.GroupLayout(MP);
        MP.setLayout(MPLayout);
        MPLayout.setHorizontalGroup(
            MPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MPLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(MPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MPLayout.createSequentialGroup()
                        .addGroup(MPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ElectronicsSp, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(GrocerySp, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BooksSp, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SportsSp, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(MyOSp, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(MyASp, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MPLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(MPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(MyCSp, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(HomeSp, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        MPLayout.setVerticalGroup(
            MPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MPLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(HomeSp, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(108, 108, 108)
                .addComponent(BooksSp, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ElectronicsSp, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(GrocerySp, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SportsSp, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(89, 89, 89)
                .addComponent(MyOSp, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(MyCSp, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(MyASp, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        SP.setBackground(new java.awt.Color(54, 33, 89));
        SP.setForeground(new java.awt.Color(255, 255, 255));

        wallet.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/icons8_wallet_40px.png"))); // NOI18N
        wallet.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        wallet.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                walletMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                walletMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                walletMouseExited(evt);
            }
        });

        log.setForeground(new java.awt.Color(255, 255, 255));
        log.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/icons8_export_32px.png"))); // NOI18N
        log.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        log.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                logMouseEntered(evt);
            }
        });

        bal.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        bal.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout SPLayout = new javax.swing.GroupLayout(SP);
        SP.setLayout(SPLayout);
        SPLayout.setHorizontalGroup(
            SPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SPLayout.createSequentialGroup()
                .addGap(499, 499, 499)
                .addComponent(wallet)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(SPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(add, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bal, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(log)
                .addGap(22, 22, 22))
        );
        SPLayout.setVerticalGroup(
            SPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SPLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(SPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(SPLayout.createSequentialGroup()
                        .addComponent(add, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SPLayout.createSequentialGroup()
                        .addGroup(SPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, SPLayout.createSequentialGroup()
                                .addComponent(wallet)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(SPLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(SPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(log, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(bal, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap())))
        );

        jLabel34.setBackground(new java.awt.Color(255, 255, 255));

        jLabel35.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel35.setText("Username");

        jLabel37.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel37.setText("Mobile No.");

        jLabel38.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel38.setText("Email-ID");

        jLabel39.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel39.setText("Gender");

        jLabel41.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel41.setText("City");

        jLabel42.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel42.setText("State");

        jLabel43.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel43.setText("Country");

        yn.setEditable(false);
        yn.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        mn.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        mn.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        eid.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        ci.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        st.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        c.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        jButton1.setBackground(new java.awt.Color(0, 255, 0));
        jButton1.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("UPDATE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        buttonGroup1.add(ml);
        ml.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        ml.setText("Male");

        buttonGroup1.add(fm);
        fm.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        fm.setText("Female");

        pre.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        pre.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "+91", "+93", "+94", "+95", "+975", "+977" }));
        pre.setSelectedIndex(-1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(MP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel37)
                            .addComponent(jLabel38)
                            .addComponent(jLabel39)
                            .addComponent(jLabel43)
                            .addComponent(jLabel41)
                            .addComponent(jLabel42)
                            .addComponent(jLabel35))
                        .addGap(63, 63, 63)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(avatar, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel34, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(yn, javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(ml)
                                    .addGap(18, 18, 18)
                                    .addComponent(fm))
                                .addComponent(eid, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(ci, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(st, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(c, javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(pre, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(mn, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(302, 302, 302)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addComponent(SP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(SP, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel34, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(avatar, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel35)
                    .addComponent(yn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel37)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(mn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pre, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(eid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel38))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(fm)
                            .addComponent(ml)
                            .addComponent(jLabel39))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ci, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel41))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(st, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel42))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(c, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel43))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BooksSymMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BooksSymMouseClicked
        Books bk= new Books(Username1);
        bk.setVisible(true);
        this.dispose();          // TODO add your handling code here:
    }//GEN-LAST:event_BooksSymMouseClicked

    private void BooksMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BooksMouseClicked
        Books bk= new Books(Username1);
        bk.setVisible(true);
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_BooksMouseClicked

    private void BooksSpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BooksSpMouseClicked
        Books bk= new Books(Username1);
        bk.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BooksSpMouseClicked

    private void HomeSpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HomeSpMouseClicked
MainInterfacee mi= new MainInterfacee(Username1);
        mi.setVisible(true);
        this.dispose();             // TODO add your handling code here:
    }//GEN-LAST:event_HomeSpMouseClicked

    private void ElectronicsSymMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ElectronicsSymMouseClicked
        Electronics er= new Electronics(Username1);
        er.setVisible(true);
        this.dispose();         // TODO add your handling code here:
    }//GEN-LAST:event_ElectronicsSymMouseClicked

    private void ElectronicsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ElectronicsMouseClicked
        Electronics er= new Electronics(Username1);
        er.setVisible(true);
        this.dispose();         // TODO add your handling code here:
    }//GEN-LAST:event_ElectronicsMouseClicked

    private void ElectronicsSpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ElectronicsSpMouseClicked
        Electronics er= new Electronics(Username1);
        er.setVisible(true);
        this.dispose();           // TODO add your handling code here:
    }//GEN-LAST:event_ElectronicsSpMouseClicked

    private void GrocerySymMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GrocerySymMouseClicked
        Grocery gr= new Grocery(Username1);
        gr.setVisible(true);
        this.dispose();         // TODO add your handling code here:
    }//GEN-LAST:event_GrocerySymMouseClicked

    private void GroceryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GroceryMouseClicked
        Grocery gr= new Grocery(Username1);
        gr.setVisible(true);
        this.dispose();         // TODO add your handling code here:
    }//GEN-LAST:event_GroceryMouseClicked

    private void GrocerySpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GrocerySpMouseClicked
        Grocery gr= new Grocery(Username1);
        gr.setVisible(true);
        this.dispose();          // TODO add your handling code here:
    }//GEN-LAST:event_GrocerySpMouseClicked

    private void SportsSymMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SportsSymMouseClicked
        SportsFitnessBags sfb= new SportsFitnessBags(Username1);
        sfb.setVisible(true);
        this.dispose();          // TODO add your handling code here:
    }//GEN-LAST:event_SportsSymMouseClicked

    private void SportsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SportsMouseClicked
        SportsFitnessBags sfb= new SportsFitnessBags(Username1);
        sfb.setVisible(true);
        this.dispose();          // TODO add your handling code here:
    }//GEN-LAST:event_SportsMouseClicked

    private void SportsSpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SportsSpMouseClicked
        SportsFitnessBags sfb= new SportsFitnessBags(Username1);
        sfb.setVisible(true);
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_SportsSpMouseClicked

    private void MyOSymMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MyOSymMouseClicked
        MyOrders mo= new MyOrders(Username1);
        mo.setVisible(true);
        this.dispose();          // TODO add your handling code here:
    }//GEN-LAST:event_MyOSymMouseClicked

    private void MyOMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MyOMouseClicked
        MyOrders mo= new MyOrders(Username1);
        mo.setVisible(true);
        this.dispose();          // TODO add your handling code here:
    }//GEN-LAST:event_MyOMouseClicked

    private void MyOSpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MyOSpMouseClicked
        MyOrders mo= new MyOrders(Username1);
        mo.setVisible(true);
        this.dispose();          // TODO add your handling code here:
    }//GEN-LAST:event_MyOSpMouseClicked

    private void MyCSymMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MyCSymMouseClicked
        MyCart myc= new MyCart(Username1);
        myc.setVisible(true);
        this.dispose();             // TODO add your handling code here:
    }//GEN-LAST:event_MyCSymMouseClicked

    private void MyCMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MyCMouseClicked
        MyCart myc= new MyCart(Username1);
        myc.setVisible(true);
        this.dispose();          // TODO add your handling code here:
    }//GEN-LAST:event_MyCMouseClicked

    private void MyCSpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MyCSpMouseClicked
        MyCart myc= new MyCart(Username1);
        myc.setVisible(true);
        this.dispose();          // TODO add your handling code here:
    }//GEN-LAST:event_MyCSpMouseClicked

    private void HomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HomeMouseClicked
MainInterfacee mi= new MainInterfacee(Username1);
        mi.setVisible(true);
        this.dispose();             // TODO add your handling code here:
    }//GEN-LAST:event_HomeMouseClicked

    private void HomeSymMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HomeSymMouseClicked
MainInterfacee mi= new MainInterfacee(Username1);
        mi.setVisible(true);
        this.dispose();             // TODO add your handling code here:
    }//GEN-LAST:event_HomeSymMouseClicked

    private void HomeSpMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HomeSpMouseEntered
 HomeSym.setIcon(new ImageIcon(getClass().getResource("/Resources/icons8_home_30px.png")));    
        HomeSp.setBackground(Color.WHITE);  
Home.setForeground(new Color(85,65,118));         // TODO add your handling code here:
    }//GEN-LAST:event_HomeSpMouseEntered

    private void HomeSpMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HomeSpMouseExited
    HomeSym.setIcon(new ImageIcon(getClass().getResource("/Resources/icons8_home_30px_1.png")));     
        HomeSp.setBackground(new Color(85,65,118));  
Home.setForeground(Color.WHITE);      // TODO add your handling code here:
    }//GEN-LAST:event_HomeSpMouseExited

    private void BooksSpMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BooksSpMouseEntered
  BooksSp.setBackground(Color.WHITE);  
Books.setForeground(new Color(85,65,118));        // TODO add your handling code here:
    }//GEN-LAST:event_BooksSpMouseEntered

    private void BooksSpMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BooksSpMouseExited
  BooksSp.setBackground(new Color(85,65,118));  
Books.setForeground(Color.WHITE);       // TODO add your handling code here:
    }//GEN-LAST:event_BooksSpMouseExited

    private void ElectronicsSpMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ElectronicsSpMouseEntered
  ElectronicsSp.setBackground(Color.WHITE);  
Electronics.setForeground(new Color(85,65,118));      // TODO add your handling code here:
    }//GEN-LAST:event_ElectronicsSpMouseEntered

    private void ElectronicsSpMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ElectronicsSpMouseExited
  ElectronicsSp.setBackground(new Color(85,65,118));  
Electronics.setForeground(Color.WHITE);       // TODO add your handling code here:
    }//GEN-LAST:event_ElectronicsSpMouseExited

    private void GrocerySpMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GrocerySpMouseEntered
 GrocerySp.setBackground(Color.WHITE);  
Grocery.setForeground(new Color(85,65,118));        // TODO add your handling code here:
    }//GEN-LAST:event_GrocerySpMouseEntered

    private void GrocerySpMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GrocerySpMouseExited
 GrocerySp.setBackground(new Color(85,65,118));  
Grocery.setForeground(Color.WHITE);            // TODO add your handling code here:
    }//GEN-LAST:event_GrocerySpMouseExited

    private void SportsSpMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SportsSpMouseEntered
  SportsSp.setBackground(Color.WHITE);  
Sports.setForeground(new Color(85,65,118));           // TODO add your handling code here:
    }//GEN-LAST:event_SportsSpMouseEntered

    private void SportsSpMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SportsSpMouseExited
 SportsSp.setBackground(new Color(85,65,118));  
Sports.setForeground(Color.WHITE);        // TODO add your handling code here:
    }//GEN-LAST:event_SportsSpMouseExited

    private void MyOSpMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MyOSpMouseEntered
    MyOSym.setIcon(new ImageIcon(getClass().getResource("/Resources/icons8_purchase_order_32px_1.png")));  
        MyOSp.setBackground(Color.WHITE);  
MyO.setForeground(new Color(85,65,118));       // TODO add your handling code here:
    }//GEN-LAST:event_MyOSpMouseEntered

    private void MyOSpMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MyOSpMouseExited
  MyOSym.setIcon(new ImageIcon(getClass().getResource("/Resources/icons8_purchase_order_32px.png")));   
        MyOSp.setBackground(new Color(85,65,118));  
MyO.setForeground(Color.WHITE);       // TODO add your handling code here:
    }//GEN-LAST:event_MyOSpMouseExited

    private void MyCSpMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MyCSpMouseEntered
     MyCSym.setIcon(new ImageIcon(getClass().getResource("/Resources/icons8_shopping_cart_30px_1.png")));  
        MyCSp.setBackground(Color.WHITE);  
MyC.setForeground(new Color(85,65,118));       // TODO add your handling code here:
    }//GEN-LAST:event_MyCSpMouseEntered

    private void MyCSpMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MyCSpMouseExited
   MyCSym.setIcon(new ImageIcon(getClass().getResource("/Resources/icons8_shopping_cart_30px.png")));  
        MyCSp.setBackground(new Color(85,65,118));  
MyC.setForeground(Color.WHITE);         // TODO add your handling code here:
    }//GEN-LAST:event_MyCSpMouseExited

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
  
 String gender = null;
Object PRE=pre.getSelectedItem();
String MN=mn.getText();
String EID=eid.getText();

String ST=st.getText();
String CI=ci.getText();
String CY=c.getText();


String PATTERNB="^[0-9]{10,10}$";  
          Pattern pattb=Pattern.compile(PATTERNB);
          Matcher matchb=pattb.matcher(MN);
          String PATTERNN="^[a-zA-Z0-9]{1,44}[@][a-zA-Z0-9]{1,10}[.][a-zA-Z]{0,5}$";  
          Pattern pattt=Pattern.compile(PATTERNN);
          Matcher matchh=pattt.matcher(EID);
          String PATTERNC="^[a-zA-Z]{0,44}$";  
          Pattern pattc=Pattern.compile(PATTERNC);
          Matcher matchc=pattc.matcher(CI);
          String PATTERND="^[a-zA-Z]{0,44}$";  
          Pattern pattd=Pattern.compile(PATTERND);
          Matcher matchd=pattd.matcher(CY);
          String PATTERNE="^[a-zA-Z]{0,44}$";  
          Pattern patte=Pattern.compile(PATTERNE);
          Matcher matche=patte.matcher(ST);
     
          
          
if(ml.isSelected()) 
{gender="Male";
avatar.setIcon(new ImageIcon(getClass().getResource("/Resources/Male.jpg")));}
else if(fm.isSelected()) 
{gender="Female";
avatar.setIcon(new ImageIcon(getClass().getResource("/Resources/Female.jpg")));}

 if (pre.getSelectedIndex()==-1)
{JOptionPane.showMessageDialog(null,"Select Country Code");}
else if (MN.equals(""))
{ JOptionPane.showMessageDialog(null,"Your Mobile No is mandatory to enter");}
else if(!matchb.matches())
      {JOptionPane.showMessageDialog(null,"Enter valid mobile number");}
else if (EID.equals(""))
{ JOptionPane.showMessageDialog(null,"Your E-mail ID is mandatory to enter");}
      else if(!matchh.matches())
      {JOptionPane.showMessageDialog(null,"Invalid Email-ID");}
else if (ml.isSelected()==false && fm.isSelected()==false)
{ JOptionPane.showMessageDialog(null,"Gender is mandatory");}
else if (CI.equals(""))
{ JOptionPane.showMessageDialog(null,"Your city is mandatory to enter");}
else if(!matchc.matches())
{JOptionPane.showMessageDialog(null,"Please enter correct City Name!");
}
else if (ST.equals(""))
{ JOptionPane.showMessageDialog(null,"Your state is mandatory to enter");}
else if(!matche.matches())
{JOptionPane.showMessageDialog(null,"Please enter corect State name!");
}
else if (CY.equals(""))
{ JOptionPane.showMessageDialog(null,"Your country name is mandatory to enter");}
else if(!matchd.matches())
{JOptionPane.showMessageDialog(null,"Please enter corect country name!");
}
// Checking genuity of user data 
else
{
        try
     {
         Class.forName("com.mysql.jdbc.Driver");
         Connection con =DriverManager.getConnection("jdbc:mysql://localhost/project2019","root","0000");
         Statement stmt=con.createStatement();

         

       String update="UPDATE user_details Set Contact_No = '"+ PRE+MN +"', Email_ID = '"+EID+"',Country='"+ CY +"', Gender='"+ gender +"', City='"+ CI +"' ,State='"+ ST +"' WHERE User_Name ='"+ Username1 +"';";
       stmt.executeUpdate(update);

       JOptionPane.showMessageDialog(null,"Update Successful");

     }
     catch(Exception e)
     {
         JOptionPane.showMessageDialog(null,"Error");
    } 
}       // Update userData
    }//GEN-LAST:event_jButton1ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
           String gen=null;
        String sql = "select Balance,User_name,Left(Contact_No,3) AS Country_Code,Right(Contact_No,10) AS Contact_No,Email_ID,Country,City,State,Gender from user_details where User_name='"+ Username1 +"';"; 
       try{ Class.forName("com.mysql.jdbc.Driver");
         Connection con =DriverManager.getConnection("jdbc:mysql://localhost/project2019","root","0000");
        Statement stmt= con.createStatement();
        ResultSet rs=stmt.executeQuery(sql); 
        
       while (rs.next()){ 
        bal.setText(rs.getString("Balance"));
        pre.setSelectedItem(rs.getString("Country_Code"));
       mn.setText(rs.getString("Contact_No"));
         eid.setText(rs.getString("Email_ID"));
           c.setText(rs.getString("Country"));
             st.setText(rs.getString("State"));
               mn.setText(rs.getString("Contact_No"));
       ci.setText(rs.getString("City"));
       gen=rs.getString("Gender");
       if (gen.equals("Male"))
       { ml.setSelected(true);fm.setSelected(false);
        avatar.setIcon(new ImageIcon(getClass().getResource("/Resources/Male.jpg")));}
       else if(gen.equals("Female"))
       {fm.setSelected(true);ml.setSelected(false);
        avatar.setIcon(new ImageIcon(getClass().getResource("/Resources/Female.jpg")));
       }
       }
       stmt.close();
       rs.close();
       con.close(); }
   catch(Exception e){       
       System.out.println("Something went wrong !! Please try again");}
       yn.setText(Username1);   // Displaying UserData  
       this.setLocationRelativeTo(null);  //centre form in the screen
    }//GEN-LAST:event_formWindowOpened

    private void walletMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_walletMouseEntered
  wallet.setToolTipText("Add Balance") ; 
        wallet.setIcon(new ImageIcon(getClass().getResource("/Resources/icons8_wallet_32px.png")));
         add.setIcon(new ImageIcon(getClass().getResource("/Resources/icons8_add_16px_1.png")));
    }//GEN-LAST:event_walletMouseEntered

    private void walletMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_walletMouseExited
    wallet.setIcon(new ImageIcon(getClass().getResource("/Resources/icons8_wallet_40px.png")));  
     add.setIcon(null); 
    }//GEN-LAST:event_walletMouseExited

    private void walletMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_walletMouseClicked
AddBalance ab= new AddBalance(Username1);
        ab.setVisible(true);
                    // AddBalance Frame gets displayed
    }//GEN-LAST:event_walletMouseClicked

    private void logMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logMouseEntered
  log.setToolTipText("LogOut");        //LogOut displayed as tooltip on logout symbol
    }//GEN-LAST:event_logMouseEntered

    private void logMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logMouseClicked
LoginForm lf= new LoginForm ();
        lf.setVisible(true);
        this.dispose();         // Login form opens similiar to logout
    }//GEN-LAST:event_logMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MyAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MyAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MyAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MyAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MyAccount().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Books;
    private javax.swing.JPanel BooksSp;
    private javax.swing.JLabel BooksSym;
    private javax.swing.JLabel Electronics;
    private javax.swing.JPanel ElectronicsSp;
    private javax.swing.JLabel ElectronicsSym;
    private javax.swing.JLabel Grocery;
    private javax.swing.JPanel GrocerySp;
    private javax.swing.JLabel GrocerySym;
    private javax.swing.JLabel Home;
    private javax.swing.JPanel HomeSp;
    private javax.swing.JLabel HomeSym;
    private javax.swing.JPanel MP;
    private javax.swing.JLabel MyA;
    private javax.swing.JPanel MyASp;
    private javax.swing.JLabel MyASym;
    private javax.swing.JLabel MyC;
    private javax.swing.JPanel MyCSp;
    private javax.swing.JLabel MyCSym;
    private javax.swing.JLabel MyO;
    private javax.swing.JPanel MyOSp;
    private javax.swing.JLabel MyOSym;
    private javax.swing.JPanel SP;
    private javax.swing.JLabel Sports;
    private javax.swing.JPanel SportsSp;
    private javax.swing.JLabel SportsSym;
    private javax.swing.JLabel add;
    private javax.swing.JLabel avatar;
    private javax.swing.JLabel bal;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField c;
    private javax.swing.JTextField ci;
    private javax.swing.JTextField eid;
    private javax.swing.JRadioButton fm;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel log;
    private javax.swing.JRadioButton ml;
    private javax.swing.JTextField mn;
    private javax.swing.JComboBox pre;
    private javax.swing.JTextField st;
    private javax.swing.JLabel wallet;
    private javax.swing.JTextField yn;
    // End of variables declaration//GEN-END:variables
}
