
import java.sql.Connection;
import java.sql.*;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author TesseracT
 */
public class Order extends javax.swing.JFrame {
 String Username1;
 int Quantity1;
 String ic1;
 Connection conn=null;
ResultSet rs=null;
PreparedStatement pst=null;
int curRow=0;
    /**
     * Creates new form Order
     */
    public Order() {
        
        initComponents();
           this.setLocationRelativeTo(null);//centre form in the screen
    }
Order(String Username,int Quantity,Object ic) {        
     Username1=Username;
     Quantity1=Quantity;
     ic1=(String) ic;
        initComponents();}
 
        
       
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        wallet = new javax.swing.JLabel();
        bal = new javax.swing.JLabel();
        add = new javax.swing.JLabel();
        back = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jpa = new javax.swing.JPanel();
        post = new javax.swing.JRadioButton();
        pre = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        cont = new javax.swing.JButton();
        jpb = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        is = new javax.swing.JTextField();
        sh = new javax.swing.JTextField();
        pd = new javax.swing.JTextField();
        tbt = new javax.swing.JTextField();
        et = new javax.swing.JTextField();
        tt = new javax.swing.JTextField();
        paysec = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        gt = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(54, 33, 89));

        wallet.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/icons8_wallet_40px.png"))); // NOI18N
        wallet.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        wallet.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                walletMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                walletMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                walletMouseExited(evt);
            }
        });

        bal.setForeground(new java.awt.Color(255, 255, 255));

        back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/icons8_Go_Back_45px.png"))); // NOI18N
        back.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(back, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(wallet)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bal, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(add, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(add, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bal, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(wallet, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                    .addComponent(back, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jpa.setBackground(new java.awt.Color(252, 252, 252));

        buttonGroup1.add(post);
        post.setText("Cash on Delivery");

        buttonGroup1.add(pre);
        pre.setText("ShopAddict Balance");

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setText("Mode Of Payment");

        cont.setText("Continue");
        cont.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpaLayout = new javax.swing.GroupLayout(jpa);
        jpa.setLayout(jpaLayout);
        jpaLayout.setHorizontalGroup(
            jpaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpaLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(post)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 76, Short.MAX_VALUE)
                .addComponent(pre)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jpaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpaLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(99, 99, 99))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpaLayout.createSequentialGroup()
                        .addComponent(cont)
                        .addGap(136, 136, 136))))
        );
        jpaLayout.setVerticalGroup(
            jpaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(34, 34, 34)
                .addGroup(jpaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(post)
                    .addComponent(pre))
                .addGap(18, 18, 18)
                .addComponent(cont)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        jpb.setBackground(new java.awt.Color(252, 252, 252));

        jLabel3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel3.setText("Item Subtotal :");

        jLabel4.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel4.setText("Shipping & Handling :");

        jLabel5.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel5.setText("Total Before Tax :");

        jLabel6.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel6.setText("Estimated Tax :");

        jLabel7.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel7.setText("Grand Total :");

        jLabel8.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel8.setText("Promos & Discounts :");

        jLabel2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 0));
        jLabel2.setText("Order Details");

        is.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        sh.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        pd.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        tbt.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        et.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        tt.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        paysec.setText("Pay Securely");
        paysec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paysecActionPerformed(evt);
            }
        });

        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel9.setText("Total :");

        gt.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        javax.swing.GroupLayout jpbLayout = new javax.swing.GroupLayout(jpb);
        jpb.setLayout(jpbLayout);
        jpbLayout.setHorizontalGroup(
            jpbLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpbLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(paysec)
                .addGap(69, 69, 69))
            .addGroup(jpbLayout.createSequentialGroup()
                .addGap(127, 127, 127)
                .addComponent(jLabel2)
                .addContainerGap(145, Short.MAX_VALUE))
            .addGroup(jpbLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jpbLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpbLayout.createSequentialGroup()
                        .addGroup(jpbLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addGroup(jpbLayout.createSequentialGroup()
                                .addGap(64, 64, 64)
                                .addComponent(jButton1))
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jpbLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tbt, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jpbLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(is, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE)
                                .addComponent(sh, javax.swing.GroupLayout.Alignment.LEADING))))
                    .addGroup(jpbLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(et, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpbLayout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tt, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpbLayout.createSequentialGroup()
                        .addGroup(jpbLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jpbLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(gt)
                            .addComponent(pd, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jpbLayout.setVerticalGroup(
            jpbLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpbLayout.createSequentialGroup()
                .addComponent(jLabel2)
                .addGap(15, 15, 15)
                .addGroup(jpbLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(is, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpbLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(sh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpbLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tbt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpbLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(et, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(jpbLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(10, 10, 10)
                .addGroup(jpbLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpbLayout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel7)
                        .addGap(67, 67, 67)
                        .addGroup(jpbLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1)
                            .addComponent(paysec)))
                    .addGroup(jpbLayout.createSequentialGroup()
                        .addComponent(pd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(gt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(267, 267, 267)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jpa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jpb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(287, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(jpa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jpb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void paysecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paysecActionPerformed
String MOP = null;String TOP =null;
double di =0,d=0,discount=0,cost=0,gtotal=0,tax=0,tbtax=0;

if(post.isSelected()) 
{MOP="Cash On Delivery";
 TOP="Postpaid";
di=1;
d=0;}

else if(pre.isSelected()) 
{MOP="ShopAddict Balance";
 TOP="Prepaid";
di=0.9;
d=0.1;}


String sql = "select Item_Name,List_Price from Items where Item_Code='"+ic1 +"';"; 
       try{ Class.forName("com.mysql.jdbc.Driver");
         Connection con =DriverManager.getConnection("jdbc:mysql://localhost/project2019","root","0000");
        
       pst=con.prepareStatement(sql);
       rs=pst.executeQuery();                    
                          
     
       while (rs.next()){ 
       String in= rs.getString("Item_Name");
       int LP= rs.getInt("List_Price");
       double SP = LP*di;
       double TLP=LP;
        double amt =TLP*Quantity1;
        
       
 
       discount=d*amt;
       cost=amt;
       tbtax=cost;
       tax=0.18*(cost);
       gtotal=tbtax+tax-discount;
     
        
        
       { try
       {
         Statement stmt=con.createStatement();
 
if(post.isSelected()){
String insert="INSERT INTO orders VALUES('"+ic1+"','"+in+"','"+ Username1 +"',"+ Quantity1 +","+LP +","+SP+",'"+MOP+"','"+TOP+"',"+ gtotal +");";
stmt.executeUpdate(insert);
JOptionPane.showMessageDialog(null,"Order Placed Successful");
}
  else if(pre.isSelected())
   { String transaction ="UPDATE user_details SET Balance=Balance-"+ gtotal +" WHERE User_Name='"+Username1+"' AND Balance>="+ gtotal +";"; 
             int rs= stmt.executeUpdate(transaction);    
   if(rs!=0) 
   {String insert2="INSERT INTO orders VALUES('"+ic1+"','"+in+"','"+ Username1 +"',"+ Quantity1 +","+LP +","+SP+",'"+MOP+"','"+TOP+"'," + gtotal + ");";
stmt.executeUpdate(insert2);
JOptionPane.showMessageDialog(null,"Transaction Successful");       
  this.dispose();}
   else{ JOptionPane.showMessageDialog(null,"Not enough Balance!");}
  } 

       
 
       }
   catch(Exception e)
   {System.out.println("Something went wrong !! Please try again");}
        
     }}}
     catch(Exception e)           
   {JOptionPane.showMessageDialog(null, e.getMessage() ,"Error", 1);}// TODO add your handling code here:
                                               // TODO add your handling code here:
    }//GEN-LAST:event_paysecActionPerformed

    private void walletMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_walletMouseClicked
        AddBalance ab= new AddBalance(Username1);
        ab.setVisible(true);
       
        // TODO add your handling code here:
    }//GEN-LAST:event_walletMouseClicked

    private void walletMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_walletMouseEntered
        wallet.setToolTipText("Add Balance") ;
        wallet.setIcon(new ImageIcon(getClass().getResource("/Resources/icons8_wallet_32px.png")));
        add.setIcon(new ImageIcon(getClass().getResource("/Resources/icons8_add_16px_1.png")));

       // TODO add your handling code here:
    }//GEN-LAST:event_walletMouseEntered

    private void walletMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_walletMouseExited
        wallet.setIcon(new ImageIcon(getClass().getResource("/Resources/icons8_wallet_40px.png")));
        add.setIcon(null);
        // TODO add your handling code here:
    }//GEN-LAST:event_walletMouseExited

    private void backMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseClicked
   this.dispose();        // Closing this frame
    }//GEN-LAST:event_backMouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
   String sql = "select Balance from user_details where User_name=('"+ Username1 +"')";
        try{ Class.forName("com.mysql.jdbc.Driver");
            Connection con =DriverManager.getConnection("jdbc:mysql://localhost/project2019","root","0000");

            pst=con.prepareStatement(sql);
            rs=pst.executeQuery();

            while (rs.next()){
                bal.setText(rs.getString("Balance"));}
        }
        catch(Exception e){
            System.out.println("Something went wrong !! Please try again");}
        jpb.setVisible(false);// TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    private void contActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contActionPerformed
String MOP = null;String TOP =null;
double d =0,di=0,cost =0,tax=0,tbtax=0,discount=0,total=0,gtotal=0;
int s=0;

if(post.isSelected()) 
{MOP="Cash On Delivery";
 TOP="Postpaid";
d=0;
di=1;
}

else if(pre.isSelected()) 
{MOP="ShopAddict Balance";
 TOP="Prepaid";
d=0.1;
di=0.9;}


String sql = "select Item_Name,List_Price from Items where Item_Code='"+ic1 +"';"; 
       try{ Class.forName("com.mysql.jdbc.Driver");
         Connection con =DriverManager.getConnection("jdbc:mysql://localhost/project2019","root","0000");
        
       pst=con.prepareStatement(sql);
       rs=pst.executeQuery();                    
                          
     
       while (rs.next()){ 
       String in= rs.getString("Item_Name");
       int LP= rs.getInt("List_Price");
        double TLP = LP;
       double amt =TLP*Quantity1;    
        
       jpa.setVisible(false);        
       discount=d*amt;
       cost=amt;
       tbtax=cost;
       tax=0.18*(cost);
       total=tbtax+tax;
       gtotal=tbtax+tax-discount;
                                                             
      is.setText(Double.toString(cost));       
        sh.setText(Integer.toString(s));     
        tbt.setText(Double.toString(tbtax));
        et.setText(Double.toString(tax));
        tt.setText(Double.toString(total));
          pd.setText(Double.toString(discount));
         gt.setText(Double.toString(gtotal));
        jpb.setVisible(true);
       }}catch(Exception e)           
   {JOptionPane.showMessageDialog(null, e.getMessage() ,"Error", 1);}// TODO add your handling code here:
    }//GEN-LAST:event_contActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
jpb.setVisible(false);
jpa.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Order.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Order.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Order.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Order.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Order().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel add;
    private javax.swing.JLabel back;
    private javax.swing.JLabel bal;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton cont;
    private javax.swing.JTextField et;
    private javax.swing.JTextField gt;
    private javax.swing.JTextField is;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jpa;
    private javax.swing.JPanel jpb;
    private javax.swing.JButton paysec;
    private javax.swing.JTextField pd;
    private javax.swing.JRadioButton post;
    private javax.swing.JRadioButton pre;
    private javax.swing.JTextField sh;
    private javax.swing.JTextField tbt;
    private javax.swing.JTextField tt;
    private javax.swing.JLabel wallet;
    // End of variables declaration//GEN-END:variables
}
