
import java.awt.Color;
import java.sql.*;
import javax.swing.ImageIcon;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author TesseracT
 */
public class SportsFitnessBags extends javax.swing.JFrame {
String Username1;
Connection conn=null;
ResultSet rs=null;
int curRow=0;
    /**
     * Creates new form SportsFitnessBags
     */
    public SportsFitnessBags() {
        initComponents();
         
    }

    SportsFitnessBags(String Username) {
          Username1=Username;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MP = new javax.swing.JPanel();
        BooksSp = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        BooksSym = new javax.swing.JLabel();
        Books = new javax.swing.JLabel();
        HomeSp = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        HomeSym = new javax.swing.JLabel();
        Home = new javax.swing.JLabel();
        ElectronicsSp = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        ElectronicsSym = new javax.swing.JLabel();
        Electronics = new javax.swing.JLabel();
        GrocerySp = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        GrocerySym = new javax.swing.JLabel();
        Grocery = new javax.swing.JLabel();
        SportsSp = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        SportsSym = new javax.swing.JLabel();
        Sports = new javax.swing.JLabel();
        MyOSp = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        MyOSym = new javax.swing.JLabel();
        MyO = new javax.swing.JLabel();
        MyCSp = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        MyCSym = new javax.swing.JLabel();
        MyC = new javax.swing.JLabel();
        MyASp = new javax.swing.JPanel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        MyASym = new javax.swing.JLabel();
        MyA = new javax.swing.JLabel();
        SGSP = new javax.swing.JPanel();
        SGSI = new javax.swing.JLabel();
        SGSC = new javax.swing.JLabel();
        SGSP1 = new javax.swing.JPanel();
        SGSI1 = new javax.swing.JLabel();
        SGSC1 = new javax.swing.JLabel();
        SGSP2 = new javax.swing.JPanel();
        SGSI2 = new javax.swing.JLabel();
        SGSC2 = new javax.swing.JLabel();
        SGSP3 = new javax.swing.JPanel();
        SGSI3 = new javax.swing.JLabel();
        SGSC3 = new javax.swing.JLabel();
        SGSP4 = new javax.swing.JPanel();
        SGSI4 = new javax.swing.JLabel();
        SGSC4 = new javax.swing.JLabel();
        SGSP5 = new javax.swing.JPanel();
        SGSI5 = new javax.swing.JLabel();
        SGSC5 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        bal = new javax.swing.JLabel();
        add = new javax.swing.JLabel();
        wallet = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        MP.setBackground(new java.awt.Color(54, 33, 89));

        BooksSp.setBackground(new java.awt.Color(85, 65, 118));
        BooksSp.setForeground(new java.awt.Color(255, 255, 255));
        BooksSp.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BooksSp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BooksSpMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BooksSpMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BooksSpMouseExited(evt);
            }
        });
        BooksSp.setLayout(new javax.swing.BoxLayout(BooksSp, javax.swing.BoxLayout.LINE_AXIS));
        BooksSp.add(jLabel1);

        jLabel4.setText("      ");
        BooksSp.add(jLabel4);

        BooksSym.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/icons8_book_shelf_30px_1.png"))); // NOI18N
        BooksSym.setText("    ");
        BooksSym.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BooksSymMouseClicked(evt);
            }
        });
        BooksSp.add(BooksSym);

        Books.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Books.setForeground(new java.awt.Color(204, 204, 204));
        Books.setText("    Books");
        Books.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Books.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BooksMouseClicked(evt);
            }
        });
        BooksSp.add(Books);

        HomeSp.setBackground(new java.awt.Color(85, 65, 118));
        HomeSp.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        HomeSp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HomeSpMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                HomeSpMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                HomeSpMouseExited(evt);
            }
        });
        HomeSp.setLayout(new javax.swing.BoxLayout(HomeSp, javax.swing.BoxLayout.LINE_AXIS));
        HomeSp.add(jLabel5);

        jLabel6.setText("      ");
        HomeSp.add(jLabel6);

        HomeSym.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/icons8_home_30px_1.png"))); // NOI18N
        HomeSym.setText("    ");
        HomeSym.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HomeSymMouseClicked(evt);
            }
        });
        HomeSp.add(HomeSym);

        Home.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Home.setForeground(new java.awt.Color(204, 204, 204));
        Home.setText("    Home");
        Home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HomeMouseClicked(evt);
            }
        });
        HomeSp.add(Home);

        ElectronicsSp.setBackground(new java.awt.Color(85, 65, 118));
        ElectronicsSp.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ElectronicsSp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ElectronicsSpMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ElectronicsSpMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ElectronicsSpMouseExited(evt);
            }
        });
        ElectronicsSp.setLayout(new javax.swing.BoxLayout(ElectronicsSp, javax.swing.BoxLayout.LINE_AXIS));
        ElectronicsSp.add(jLabel9);

        jLabel10.setText("      ");
        ElectronicsSp.add(jLabel10);

        ElectronicsSym.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/icons8_electronics_30px_1.png"))); // NOI18N
        ElectronicsSym.setText("    ");
        ElectronicsSym.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ElectronicsSymMouseClicked(evt);
            }
        });
        ElectronicsSp.add(ElectronicsSym);

        Electronics.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Electronics.setForeground(new java.awt.Color(204, 204, 204));
        Electronics.setText("    Electronics");
        Electronics.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ElectronicsMouseClicked(evt);
            }
        });
        ElectronicsSp.add(Electronics);

        GrocerySp.setBackground(new java.awt.Color(85, 65, 118));
        GrocerySp.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        GrocerySp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                GrocerySpMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                GrocerySpMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                GrocerySpMouseExited(evt);
            }
        });
        GrocerySp.setLayout(new javax.swing.BoxLayout(GrocerySp, javax.swing.BoxLayout.LINE_AXIS));
        GrocerySp.add(jLabel13);

        jLabel14.setText("      ");
        GrocerySp.add(jLabel14);

        GrocerySym.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/icons8_grocery_bag_30px.png"))); // NOI18N
        GrocerySym.setText("    ");
        GrocerySym.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                GrocerySymMouseClicked(evt);
            }
        });
        GrocerySp.add(GrocerySym);

        Grocery.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Grocery.setForeground(new java.awt.Color(204, 204, 204));
        Grocery.setText("    Grocery");
        Grocery.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                GroceryMouseClicked(evt);
            }
        });
        GrocerySp.add(Grocery);

        SportsSp.setBackground(new java.awt.Color(255, 255, 255));
        SportsSp.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        SportsSp.setLayout(new javax.swing.BoxLayout(SportsSp, javax.swing.BoxLayout.LINE_AXIS));
        SportsSp.add(jLabel17);

        jLabel18.setText("      ");
        SportsSp.add(jLabel18);

        SportsSym.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/icons8_volleyball_2_30px_1.png"))); // NOI18N
        SportsSym.setText("    ");
        SportsSp.add(SportsSym);

        Sports.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Sports.setForeground(new java.awt.Color(85, 65, 118));
        Sports.setText("    Sports,Fitness & Bags ");
        Sports.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        SportsSp.add(Sports);

        MyOSp.setBackground(new java.awt.Color(85, 65, 118));
        MyOSp.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        MyOSp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MyOSpMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                MyOSpMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                MyOSpMouseExited(evt);
            }
        });
        MyOSp.setLayout(new javax.swing.BoxLayout(MyOSp, javax.swing.BoxLayout.LINE_AXIS));
        MyOSp.add(jLabel21);

        jLabel23.setText("     ");
        MyOSp.add(jLabel23);

        MyOSym.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/icons8_purchase_order_32px_2.png"))); // NOI18N
        MyOSym.setText("      ");
        MyOSym.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MyOSymMouseClicked(evt);
            }
        });
        MyOSp.add(MyOSym);

        MyO.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        MyO.setForeground(new java.awt.Color(204, 204, 204));
        MyO.setText("     My Orders");
        MyO.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MyOMouseClicked(evt);
            }
        });
        MyOSp.add(MyO);

        MyCSp.setBackground(new java.awt.Color(85, 65, 118));
        MyCSp.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        MyCSp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MyCSpMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                MyCSpMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                MyCSpMouseExited(evt);
            }
        });
        MyCSp.setLayout(new javax.swing.BoxLayout(MyCSp, javax.swing.BoxLayout.LINE_AXIS));
        MyCSp.add(jLabel25);

        jLabel26.setText("      ");
        MyCSp.add(jLabel26);

        MyCSym.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/icons8_shopping_cart_30px.png"))); // NOI18N
        MyCSym.setText("    ");
        MyCSym.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MyCSymMouseClicked(evt);
            }
        });
        MyCSp.add(MyCSym);

        MyC.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        MyC.setForeground(new java.awt.Color(204, 204, 204));
        MyC.setText("      My Cart");
        MyC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MyCMouseClicked(evt);
            }
        });
        MyCSp.add(MyC);

        MyASp.setBackground(new java.awt.Color(85, 65, 118));
        MyASp.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        MyASp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MyASpMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                MyASpMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                MyASpMouseExited(evt);
            }
        });
        MyASp.setLayout(new javax.swing.BoxLayout(MyASp, javax.swing.BoxLayout.LINE_AXIS));
        MyASp.add(jLabel29);

        jLabel30.setText("      ");
        MyASp.add(jLabel30);

        MyASym.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/icons8_user_male_circle_30px.png"))); // NOI18N
        MyASym.setText("    ");
        MyASym.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MyASymMouseClicked(evt);
            }
        });
        MyASp.add(MyASym);

        MyA.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        MyA.setForeground(new java.awt.Color(204, 204, 204));
        MyA.setText("      My Account");
        MyA.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MyAMouseClicked(evt);
            }
        });
        MyASp.add(MyA);

        javax.swing.GroupLayout MPLayout = new javax.swing.GroupLayout(MP);
        MP.setLayout(MPLayout);
        MPLayout.setHorizontalGroup(
            MPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MPLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(MPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MPLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(MyCSp, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(MPLayout.createSequentialGroup()
                        .addGroup(MPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ElectronicsSp, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(GrocerySp, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BooksSp, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SportsSp, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(HomeSp, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(MyOSp, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(MyASp, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        MPLayout.setVerticalGroup(
            MPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MPLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(HomeSp, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(108, 108, 108)
                .addComponent(BooksSp, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ElectronicsSp, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(GrocerySp, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SportsSp, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(89, 89, 89)
                .addComponent(MyOSp, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(MyCSp, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(MyASp, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        SGSP.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        SGSP.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        SGSP.setPreferredSize(new java.awt.Dimension(340, 495));

        SGSI.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Badminton.jpeg"))); // NOI18N
        SGSI.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        SGSI.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SGSIMouseClicked(evt);
            }
        });

        SGSC.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        SGSC.setText("Adrenex R301 String Badminton Racquet");

        javax.swing.GroupLayout SGSPLayout = new javax.swing.GroupLayout(SGSP);
        SGSP.setLayout(SGSPLayout);
        SGSPLayout.setHorizontalGroup(
            SGSPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SGSPLayout.createSequentialGroup()
                .addGroup(SGSPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(SGSPLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(SGSC))
                    .addGroup(SGSPLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(SGSI)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        SGSPLayout.setVerticalGroup(
            SGSPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SGSPLayout.createSequentialGroup()
                .addComponent(SGSI)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(SGSC))
        );

        SGSP1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        SGSP1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        SGSP1.setPreferredSize(new java.awt.Dimension(340, 495));

        SGSI1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Exercise1.jpeg"))); // NOI18N
        SGSI1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        SGSC1.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        SGSC1.setText("Iris Pedometer Cross Trainer (Grey)");

        javax.swing.GroupLayout SGSP1Layout = new javax.swing.GroupLayout(SGSP1);
        SGSP1.setLayout(SGSP1Layout);
        SGSP1Layout.setHorizontalGroup(
            SGSP1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SGSP1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(SGSP1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(SGSC1)
                    .addComponent(SGSI1))
                .addGap(27, 27, 27))
        );
        SGSP1Layout.setVerticalGroup(
            SGSP1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SGSP1Layout.createSequentialGroup()
                .addComponent(SGSI1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SGSC1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        SGSP2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        SGSP2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        SGSP2.setPreferredSize(new java.awt.Dimension(340, 495));

        SGSI2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/MedicineBall.jpeg"))); // NOI18N
        SGSI2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        SGSC2.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        SGSC2.setText("Adrenex 3kg Rubber MedicineBall");

        javax.swing.GroupLayout SGSP2Layout = new javax.swing.GroupLayout(SGSP2);
        SGSP2.setLayout(SGSP2Layout);
        SGSP2Layout.setHorizontalGroup(
            SGSP2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SGSP2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(SGSP2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(SGSP2Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(SGSC2))
                    .addComponent(SGSI2))
                .addGap(25, 25, 25))
        );
        SGSP2Layout.setVerticalGroup(
            SGSP2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SGSP2Layout.createSequentialGroup()
                .addComponent(SGSI2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SGSC2)
                .addContainerGap())
        );

        SGSP3.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        SGSP3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        SGSP3.setPreferredSize(new java.awt.Dimension(340, 495));

        SGSI3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Mat.jpeg"))); // NOI18N
        SGSI3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        SGSC3.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        SGSC3.setText("Fitnesslife Yoga Mat Blue 8mm ");

        javax.swing.GroupLayout SGSP3Layout = new javax.swing.GroupLayout(SGSP3);
        SGSP3.setLayout(SGSP3Layout);
        SGSP3Layout.setHorizontalGroup(
            SGSP3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SGSP3Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(SGSP3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SGSI3)
                    .addGroup(SGSP3Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(SGSC3)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        SGSP3Layout.setVerticalGroup(
            SGSP3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SGSP3Layout.createSequentialGroup()
                .addComponent(SGSI3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(SGSC3)
                .addContainerGap())
        );

        SGSP4.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        SGSP4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        SGSP4.setPreferredSize(new java.awt.Dimension(340, 495));

        SGSI4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/VectorFootball.jpeg"))); // NOI18N
        SGSI4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        SGSC4.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        SGSC4.setText("Vector X ATTACKER Football ");

        javax.swing.GroupLayout SGSP4Layout = new javax.swing.GroupLayout(SGSP4);
        SGSP4.setLayout(SGSP4Layout);
        SGSP4Layout.setHorizontalGroup(
            SGSP4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SGSP4Layout.createSequentialGroup()
                .addGroup(SGSP4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(SGSP4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(SGSI4))
                    .addGroup(SGSP4Layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(SGSC4)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        SGSP4Layout.setVerticalGroup(
            SGSP4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SGSP4Layout.createSequentialGroup()
                .addComponent(SGSI4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(SGSC4)
                .addContainerGap())
        );

        SGSP5.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        SGSP5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        SGSP5.setPreferredSize(new java.awt.Dimension(340, 495));

        SGSI5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/CricketBatSS.jpeg"))); // NOI18N
        SGSI5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        SGSC5.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        SGSC5.setText("SS MASTER English Willow Cricket Bat (0.1kg)");

        javax.swing.GroupLayout SGSP5Layout = new javax.swing.GroupLayout(SGSP5);
        SGSP5.setLayout(SGSP5Layout);
        SGSP5Layout.setHorizontalGroup(
            SGSP5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SGSP5Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(SGSI5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SGSP5Layout.createSequentialGroup()
                .addGap(0, 8, Short.MAX_VALUE)
                .addComponent(SGSC5))
        );
        SGSP5Layout.setVerticalGroup(
            SGSP5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SGSP5Layout.createSequentialGroup()
                .addComponent(SGSI5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(SGSC5))
        );

        jPanel12.setBackground(new java.awt.Color(54, 33, 89));

        bal.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        bal.setForeground(new java.awt.Color(255, 255, 255));

        wallet.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/icons8_wallet_40px.png"))); // NOI18N
        wallet.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        wallet.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                walletMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                walletMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                walletMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(wallet)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bal, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(add, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addComponent(wallet, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addComponent(add, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bal, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 18, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(MP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(SGSP1, javax.swing.GroupLayout.DEFAULT_SIZE, 310, Short.MAX_VALUE)
                            .addComponent(SGSP, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(SGSP2, javax.swing.GroupLayout.DEFAULT_SIZE, 329, Short.MAX_VALUE)
                            .addComponent(SGSP5, javax.swing.GroupLayout.DEFAULT_SIZE, 329, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(SGSP4, javax.swing.GroupLayout.DEFAULT_SIZE, 308, Short.MAX_VALUE)
                            .addComponent(SGSP3, javax.swing.GroupLayout.DEFAULT_SIZE, 308, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SGSP4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(SGSP5, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(SGSP, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SGSP1, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(SGSP3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 371, Short.MAX_VALUE)
                        .addComponent(SGSP2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 371, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BooksMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BooksMouseClicked
        Books bk= new Books(Username1);
        bk.setVisible(true);
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_BooksMouseClicked

    private void MyOMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MyOMouseClicked
MyOrders mo= new MyOrders(Username1);
        mo.setVisible(true);
        this.dispose();          // TODO add your handling code here:
    }//GEN-LAST:event_MyOMouseClicked

    private void ElectronicsSymMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ElectronicsSymMouseClicked
Electronics er= new Electronics(Username1);
        er.setVisible(true);
        this.dispose();         // TODO add your handling code here:
    }//GEN-LAST:event_ElectronicsSymMouseClicked

    private void ElectronicsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ElectronicsMouseClicked
Electronics er= new Electronics(Username1);
        er.setVisible(true);
        this.dispose();         // TODO add your handling code here:
    }//GEN-LAST:event_ElectronicsMouseClicked

    private void BooksSymMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BooksSymMouseClicked
Books bk= new Books(Username1);
        bk.setVisible(true);
        this.dispose();           // TODO add your handling code here:
    }//GEN-LAST:event_BooksSymMouseClicked

    private void GrocerySymMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GrocerySymMouseClicked
Grocery gr= new Grocery(Username1);
        gr.setVisible(true);
        this.dispose();            // TODO add your handling code here:
    }//GEN-LAST:event_GrocerySymMouseClicked

    private void GroceryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GroceryMouseClicked
Grocery gr= new Grocery(Username1);
        gr.setVisible(true);
        this.dispose();            // TODO add your handling code here:
    }//GEN-LAST:event_GroceryMouseClicked

    private void HomeSymMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HomeSymMouseClicked
MainInterfacee mi= new MainInterfacee(Username1);
        mi.setVisible(true);
        this.dispose();          // TODO add your handling code here:
    }//GEN-LAST:event_HomeSymMouseClicked

    private void HomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HomeMouseClicked
MainInterfacee mi= new MainInterfacee(Username1);
        mi.setVisible(true);
        this.dispose();           // TODO add your handling code here:
    }//GEN-LAST:event_HomeMouseClicked

    private void HomeSpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HomeSpMouseClicked
MainInterfacee mi= new MainInterfacee(Username1);
        mi.setVisible(true);
        this.dispose();             // TODO add your handling code here:
    }//GEN-LAST:event_HomeSpMouseClicked

    private void MyOSymMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MyOSymMouseClicked
MyOrders mo= new MyOrders(Username1);
        mo.setVisible(true);
        this.dispose();          // TODO add your handling code here:
    }//GEN-LAST:event_MyOSymMouseClicked

    private void MyOSpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MyOSpMouseClicked
MyOrders mo= new MyOrders(Username1);
        mo.setVisible(true);
        this.dispose();          // TODO add your handling code here:
    }//GEN-LAST:event_MyOSpMouseClicked

    private void MyCSymMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MyCSymMouseClicked
MyCart myc= new MyCart(Username1);
        myc.setVisible(true);
        this.dispose();          // TODO add your handling code here:
    }//GEN-LAST:event_MyCSymMouseClicked

    private void MyCMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MyCMouseClicked
MyCart myc= new MyCart(Username1);
        myc.setVisible(true);
        this.dispose();             // TODO add your handling code here:        // TODO add your handling code here:
    }//GEN-LAST:event_MyCMouseClicked

    private void MyCSpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MyCSpMouseClicked
MyCart myc= new MyCart(Username1);
        myc.setVisible(true);
        this.dispose();             // TODO add your handling code here:
    }//GEN-LAST:event_MyCSpMouseClicked

    private void MyASymMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MyASymMouseClicked
MyAccount ma= new MyAccount(Username1);
        ma.setVisible(true);
        this.dispose();                  // TODO add your handling code here:
    }//GEN-LAST:event_MyASymMouseClicked

    private void MyAMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MyAMouseClicked
MyAccount ma= new MyAccount(Username1);
        ma.setVisible(true);
        this.dispose();                  // TODO add your handling code here:
    }//GEN-LAST:event_MyAMouseClicked

    private void MyASpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MyASpMouseClicked
MyAccount ma= new MyAccount(Username1);
        ma.setVisible(true);
        this.dispose();                  // TODO add your handling code here:
    }//GEN-LAST:event_MyASpMouseClicked

    private void SGSIMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SGSIMouseClicked
        AdrenexBd ab= new AdrenexBd(Username1);
        ab.setVisible(true);
        this.dispose();    // TODO add your handling code here:
    }//GEN-LAST:event_SGSIMouseClicked

    private void BooksSpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BooksSpMouseClicked
 Books bk= new Books(Username1);
        bk.setVisible(true);
        this.dispose();           // TODO add your handling code here:
    }//GEN-LAST:event_BooksSpMouseClicked

    private void ElectronicsSpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ElectronicsSpMouseClicked
Electronics er= new Electronics(Username1);
        er.setVisible(true);
        this.dispose();             // TODO add your handling code here:
    }//GEN-LAST:event_ElectronicsSpMouseClicked

    private void GrocerySpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GrocerySpMouseClicked
Grocery gr= new Grocery(Username1);
        gr.setVisible(true);
        this.dispose();          // TODO add your handling code here:
    }//GEN-LAST:event_GrocerySpMouseClicked

    private void HomeSpMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HomeSpMouseEntered
 HomeSym.setIcon(new ImageIcon(getClass().getResource("/Resources/icons8_home_30px.png")));    
        HomeSp.setBackground(Color.WHITE);  
Home.setForeground(new Color(85,65,118));       // TODO add your handling code here:
    }//GEN-LAST:event_HomeSpMouseEntered

    private void HomeSpMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HomeSpMouseExited
  HomeSym.setIcon(new ImageIcon(getClass().getResource("/Resources/icons8_home_30px_1.png")));     
        HomeSp.setBackground(new Color(85,65,118));  
Home.setForeground(Color.WHITE);        // TODO add your handling code here:
    }//GEN-LAST:event_HomeSpMouseExited

    private void BooksSpMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BooksSpMouseEntered
 BooksSp.setBackground(Color.WHITE);  
Books.setForeground(new Color(85,65,118));       // TODO add your handling code here:
    }//GEN-LAST:event_BooksSpMouseEntered

    private void BooksSpMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BooksSpMouseExited
 BooksSp.setBackground(new Color(85,65,118));  
Books.setForeground(Color.WHITE);         // TODO add your handling code here:
    }//GEN-LAST:event_BooksSpMouseExited

    private void ElectronicsSpMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ElectronicsSpMouseEntered
 ElectronicsSp.setBackground(Color.WHITE);  
Electronics.setForeground(new Color(85,65,118));       // TODO add your handling code here:
    }//GEN-LAST:event_ElectronicsSpMouseEntered

    private void ElectronicsSpMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ElectronicsSpMouseExited
 ElectronicsSp.setBackground(new Color(85,65,118));  
Electronics.setForeground(Color.WHITE);       // TODO add your handling code here:
    }//GEN-LAST:event_ElectronicsSpMouseExited

    private void GrocerySpMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GrocerySpMouseEntered
 GrocerySp.setBackground(Color.WHITE);  
Grocery.setForeground(new Color(85,65,118));         // TODO add your handling code here:
    }//GEN-LAST:event_GrocerySpMouseEntered

    private void GrocerySpMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GrocerySpMouseExited
 GrocerySp.setBackground(new Color(85,65,118));  
Grocery.setForeground(Color.WHITE);            // TODO add your handling code here:
    }//GEN-LAST:event_GrocerySpMouseExited

    private void MyOSpMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MyOSpMouseEntered
 MyOSym.setIcon(new ImageIcon(getClass().getResource("/Resources/icons8_purchase_order_32px_1.png")));  
        MyOSp.setBackground(Color.WHITE);  
MyO.setForeground(new Color(85,65,118));       // TODO add your handling code here:
    }//GEN-LAST:event_MyOSpMouseEntered

    private void MyOSpMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MyOSpMouseExited
   MyOSym.setIcon(new ImageIcon(getClass().getResource("/Resources/icons8_purchase_order_32px.png")));   
        MyOSp.setBackground(new Color(85,65,118));  
MyO.setForeground(Color.WHITE);       // TODO add your handling code here:
    }//GEN-LAST:event_MyOSpMouseExited

    private void MyCSpMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MyCSpMouseEntered
     MyCSym.setIcon(new ImageIcon(getClass().getResource("/Resources/icons8_shopping_cart_30px_1.png")));  
        MyCSp.setBackground(Color.WHITE);  
MyC.setForeground(new Color(85,65,118));     // TODO add your handling code here:
    }//GEN-LAST:event_MyCSpMouseEntered

    private void MyCSpMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MyCSpMouseExited
  MyCSym.setIcon(new ImageIcon(getClass().getResource("/Resources/icons8_shopping_cart_30px.png")));  
        MyCSp.setBackground(new Color(85,65,118));  
MyC.setForeground(Color.WHITE);          // TODO add your handling code here:
    }//GEN-LAST:event_MyCSpMouseExited

    private void MyASpMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MyASpMouseEntered
  MyASym.setIcon(new ImageIcon(getClass().getResource("/Resources/icons8_user_male_circle_30px_1.png")));  
        MyASp.setBackground(Color.WHITE);  
MyA.setForeground(new Color(85,65,118));      // TODO add your handling code here:
    }//GEN-LAST:event_MyASpMouseEntered

    private void MyASpMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MyASpMouseExited
 MyASym.setIcon(new ImageIcon(getClass().getResource("/Resources/icons8_user_male_circle_30px.png")));  
        MyASp.setBackground(new Color(85,65,118));  
MyA.setForeground(Color.WHITE);         // TODO add your handling code here:
    }//GEN-LAST:event_MyASpMouseExited

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
 String sql = "select Balance from user_details where User_name=('"+ Username1 +"')"; 
       try{ Class.forName("com.mysql.jdbc.Driver");
         Connection con =DriverManager.getConnection("jdbc:mysql://localhost/project2019","root","0000");       
      Statement stmt=con.createStatement();
     rs = stmt.executeQuery(sql);                                                   
      while (rs.next()){ 
        bal.setText(rs.getString("Balance"));}
          stmt.close();
       rs.close();
       con.close();     }
   catch(Exception e){       
       System.out.println("Something went wrong !! Please try again");} 
       this.setLocationRelativeTo(null);  //centre form in the screen
    }//GEN-LAST:event_formWindowOpened

    private void walletMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_walletMouseClicked
        AddBalance ab= new AddBalance(Username1);
        ab.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_walletMouseClicked

    private void walletMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_walletMouseEntered
        wallet.setToolTipText("Add Balance") ;
        wallet.setIcon(new ImageIcon(getClass().getResource("/Resources/icons8_wallet_32px.png")));
        add.setIcon(new ImageIcon(getClass().getResource("/Resources/icons8_add_16px_1.png")));
       // TODO add your handling code here:
    }//GEN-LAST:event_walletMouseEntered

    private void walletMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_walletMouseExited
        wallet.setIcon(new ImageIcon(getClass().getResource("/Resources/icons8_wallet_40px.png")));
        add.setIcon(null);
        // TODO add your handling code here:
    }//GEN-LAST:event_walletMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SportsFitnessBags.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SportsFitnessBags.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SportsFitnessBags.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SportsFitnessBags.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SportsFitnessBags().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Books;
    private javax.swing.JPanel BooksSp;
    private javax.swing.JLabel BooksSym;
    private javax.swing.JLabel Electronics;
    private javax.swing.JPanel ElectronicsSp;
    private javax.swing.JLabel ElectronicsSym;
    private javax.swing.JLabel Grocery;
    private javax.swing.JPanel GrocerySp;
    private javax.swing.JLabel GrocerySym;
    private javax.swing.JLabel Home;
    private javax.swing.JPanel HomeSp;
    private javax.swing.JLabel HomeSym;
    private javax.swing.JPanel MP;
    private javax.swing.JLabel MyA;
    private javax.swing.JPanel MyASp;
    private javax.swing.JLabel MyASym;
    private javax.swing.JLabel MyC;
    private javax.swing.JPanel MyCSp;
    private javax.swing.JLabel MyCSym;
    private javax.swing.JLabel MyO;
    private javax.swing.JPanel MyOSp;
    private javax.swing.JLabel MyOSym;
    private javax.swing.JLabel SGSC;
    private javax.swing.JLabel SGSC1;
    private javax.swing.JLabel SGSC2;
    private javax.swing.JLabel SGSC3;
    private javax.swing.JLabel SGSC4;
    private javax.swing.JLabel SGSC5;
    private javax.swing.JLabel SGSI;
    private javax.swing.JLabel SGSI1;
    private javax.swing.JLabel SGSI2;
    private javax.swing.JLabel SGSI3;
    private javax.swing.JLabel SGSI4;
    private javax.swing.JLabel SGSI5;
    private javax.swing.JPanel SGSP;
    private javax.swing.JPanel SGSP1;
    private javax.swing.JPanel SGSP2;
    private javax.swing.JPanel SGSP3;
    private javax.swing.JPanel SGSP4;
    private javax.swing.JPanel SGSP5;
    private javax.swing.JLabel Sports;
    private javax.swing.JPanel SportsSp;
    private javax.swing.JLabel SportsSym;
    private javax.swing.JLabel add;
    private javax.swing.JLabel bal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JLabel wallet;
    // End of variables declaration//GEN-END:variables
}
